/**
 * Les Aiguilles Blanches - Level Definitions
 * All level configurations for Phaser 3 version
 */

const LEVELS = [
    {
        id: 0,
        nameKey: 'tutorialName',
        taskKey: 'tutorialTask',
        difficulty: 'tutorial',
        timeLimit: 900, // 15 minutes for learning
        targetCoverage: 40,
        width: 15, // Smaller for tutorial
        height: 20,
        hasWinch: false,
        isNight: false,
        weather: 'clear',
        obstacles: [],
        isTutorial: true,
        introDialogue: 'tutorialIntro',
        tutorialSteps: [
            { trigger: 'start', dialogue: 'tutorialWelcome', delay: 1000 },
            { trigger: 'welcomeDone', dialogue: 'tutorialControls', delay: 3000 },
            { trigger: 'controlsDone', dialogue: 'tutorialMove', delay: 3000 },
            { trigger: 'moved', dialogue: 'tutorialGroomIntro' },
            { trigger: 'groomIntroDone', dialogue: 'tutorialGroomAction', delay: 3000 },
            { trigger: 'groomed', dialogue: 'tutorialCoverage' },
            { trigger: 'coverage20', dialogue: 'tutorialHUD' },
            { trigger: 'hudDone', dialogue: 'tutorialGoal', delay: 4000 },
            { trigger: 'coverage40', dialogue: 'tutorialComplete' }
        ]
    },
    {
        id: 1,
        nameKey: 'level1Name',
        taskKey: 'level1Task',
        difficulty: 'green',
        timeLimit: 300,
        targetCoverage: 80,
        width: 40,
        height: 60,
        hasWinch: false,
        isNight: false,
        weather: 'clear',
        obstacles: ['trees'],
        introDialogue: 'jeanPierreIntro'
    },
    {
        id: 2,
        nameKey: 'level2Name',
        taskKey: 'level2Task',
        difficulty: 'blue',
        timeLimit: 240,
        targetCoverage: 85,
        width: 50,
        height: 70,
        hasWinch: false,
        isNight: false,
        weather: 'clear',
        obstacles: ['trees', 'rocks'],
        introDialogue: 'level2Intro'
    },
    {
        id: 3,
        nameKey: 'level3Name',
        taskKey: 'level3Task',
        difficulty: 'park',
        timeLimit: 300,
        targetCoverage: 90,
        width: 45,
        height: 50,
        hasWinch: false,
        isNight: false,
        weather: 'clear',
        obstacles: ['jumps', 'rails'],
        specialFeatures: ['kickers', 'rails'],
        introDialogue: 'level3Intro'
    },
    {
        id: 4,
        nameKey: 'level4Name',
        taskKey: 'level4Task',
        difficulty: 'red',
        timeLimit: 280,
        targetCoverage: 80,
        width: 35,
        height: 80,
        hasWinch: false,
        isNight: false,
        weather: 'clear',
        obstacles: ['trees', 'rocks', 'pylons'],
        steepSections: true,
        introDialogue: 'level4Intro'
    },
    {
        id: 5,
        nameKey: 'level5Name',
        taskKey: 'level5Task',
        difficulty: 'park',
        timeLimit: 360,
        targetCoverage: 95,
        width: 20,
        height: 60,
        hasWinch: false,
        isNight: false,
        weather: 'clear',
        specialFeatures: ['halfpipe'],
        introDialogue: 'level5Intro'
    },
    {
        id: 6,
        nameKey: 'level6Name',
        taskKey: 'level6Task',
        difficulty: 'black',
        timeLimit: 360,
        targetCoverage: 75,
        width: 30,
        height: 90,
        hasWinch: true,
        isNight: true,
        weather: 'clear',
        obstacles: ['trees', 'rocks', 'cliffs'],
        hasDangerousBoundaries: true,
        introDialogue: 'level6Intro'
    },
    {
        id: 7,
        nameKey: 'level7Name',
        taskKey: 'level7Task',
        difficulty: 'black',
        timeLimit: 300,
        targetCoverage: 70,
        width: 40,
        height: 70,
        hasWinch: true,
        isNight: false,
        weather: 'light_snow',
        obstacles: ['avalanche_zones'],
        hazards: ['avalanche'],
        hasDangerousBoundaries: true,
        introDialogue: 'thierryWarning'
    },
    {
        id: 8,
        nameKey: 'level8Name',
        taskKey: 'level8Task',
        difficulty: 'red',
        timeLimit: 420,
        targetCoverage: 85,
        width: 60,
        height: 80,
        hasWinch: true,
        isNight: false,
        weather: 'storm',
        obstacles: ['trees', 'rocks', 'snow_drifts'],
        hasDangerousBoundaries: true,
        introDialogue: 'level8Intro'
    }
];
