/**
 * Les Aiguilles Blanches - Localization
 * Multi-language support for Phaser 3 version
 */

import { STORAGE_KEYS } from './storageKeys';
import { getString, setString } from '../utils/storage';

export type SupportedLanguage = 'fr' | 'en' | 'de' | 'it' | 'es';

let currentLang: SupportedLanguage = 'fr';

export const TRANSLATIONS: Record<SupportedLanguage, Record<string, string>> = {
    fr: {
        // Menu
        subtitle: "Simulateur de Damage",
        startGame: "Commencer",
        resumeGame: "Reprendre",
        newGame: "Nouvelle partie",
        continue: "Continuer",
        settings: "Paramètres",
        controls: "Contrôles",
        changelog: "Nouveautés",
        howToPlay: "Comment jouer",
        fullscreen: "Plein écran",
        fullscreenHint: "Appuyez sur F pour le plein écran",
        exitFullscreen: "Quitter plein écran",
        back: "Retour",
        backToGame: "Retour au jeu",
        loading: "Chargement...",
        madeIn: "Fait avec ❄️ en Savoie",
        on: "✓ OUI",
        off: "✗ NON",
        zoneClosed: "🚫 ZONE FERMÉE",
        
        // Settings
        language: "Langue",
        accessibility: "Accessibilité",
        highContrast: "Contraste élevé",
        reducedMotion: "Mouvement réduit",
        colorblindMode: "Daltonisme",
        none: "Aucun",
        deuteranopia: "Deutér.",
        protanopia: "Protan.",
        tritanopia: "Tritan.",
        
        // Controls
        move: "Déplacer",
        moveUp: "Haut",
        moveDown: "Bas",
        moveLeft: "Gauche",
        moveRight: "Droite",
        groom: "Damer",
        winch: "Treuil",
        pause: "Pause",
        clickToRebind: "Cliquer pour modifier",
        pressKey: "Appuyez sur une touche...",
        pressGamepadButton: "Appuyez sur un bouton de manette...",
        gamepadButtons: "Boutons manette",
        saved: "Sauvegardé !",
        resetControls: "Réinitialiser",
        controlsReset: "Contrôles réinitialisés !",
        movementSensitivity: "Sensibilité",
        gamepadSupported: "Manette OK",
        touchSupported: "Tactile OK",
        keyboardLayout: "Disposition clavier",
        customBindings: "Personnalisé",
        noGamepadConnected: "Aucune manette connectée",

        // Audio
        audio: "Audio",
        masterVolume: "Volume principal",
        musicVolume: "Musique",
        sfxVolume: "Effets sonores",
        voiceVolume: "Voix",
        ambienceVolume: "Ambiance",
        mute: "Muet",
        
        // How to Play hints
        howToPlayMove: "{keys} ou Flèches pour se déplacer",
        howToPlayMoveTouch: "Utilisez le D-pad virtuel",
        howToPlayMoveGamepad: "Stick ou D-pad pour se déplacer",
        howToPlayMoveHybrid: "{keys}/Flèches ou D-pad tactile",
        howToPlayGroom: "{groomKey} pour damer la neige",
        howToPlayGroomTouch: "Touchez ❄️ pour damer",
        howToPlayGroomGamepad: "pour damer la neige",
        howToPlayGroomHybrid: "{groomKey} ou touchez ❄️ pour damer",
        howToPlayFuel: "Surveillez carburant et endurance !",
        
        // Winch
        winchAttached: "🔗 Treuil attaché ! Maintenir {winchKey} pour assistance.",
        winchActive: "TREUIL",
        winchHint: "Appuyez sur {winchKey} près d'un ancrage numéroté pour utiliser le treuil",
        winchHintTouch: "Maintenir 🔗 pour le treuil",
        accessPath: "Route de service",
        toPiste: "Vers la piste",
        
        // Taunts - Cliff falls (emphasize the dramatic fall, insurance headaches, rescue hassle)
        tauntCliff1: "9 tonnes dans le ravin. L'assurance va adorer.",
        tauntCliff2: "Jean-Pierre t'avait dit : 'Pas trop près du bord !' Tu te souviens ?",
        tauntCliff3: "Les pisteurs descendent avec les cordes. Encore.",
        tauntCliff4: "Marie annule ta réservation pour la raclette de ce soir.",
        tauntCliff5: "Thierry calcule déjà le coût des réparations...",
        
        // Taunts - Fuel empty (emphasize planning failure, team disappointment)
        tauntFuel1: "La jauge était sur rouge depuis 10 minutes. Tu regardais quoi ?",
        tauntFuel2: "Émilie t'avait pourtant mis 'FAIRE LE PLEIN' en majuscules.",
        tauntFuel3: "Même le diesel a ses limites. Toi aussi, apparemment.",
        tauntFuel4: "Jean-Pierre soupire. Il envoie Thierry avec un jerrican.",
        tauntFuel5: "Le soleil se lève. La piste n'est pas damée. Les skieurs arrivent.",
        
        // Taunts - Time limit (emphasize consequences for skiers and competition)
        tauntTime1: "Premier télésiège dans 3... 2... 1... Raté.",
        tauntTime2: "Les skieurs découvrent ta piste. Bosselée. Verglacée. Magnifique.",
        tauntTime3: "Jean-Pierre regarde sa montre, puis toi, puis sa montre.",
        tauntTime4: "La FIS demande pourquoi le slalom est sur de la soupe.",
        tauntTime5: "Tu entends les moniteurs ESF expliquer aux clients pourquoi c'est 'pas de ta faute'.",
        
        // Game
        paused: "Pause",
        resume: "Reprendre",
        quitToMenu: "Retour au menu",
        levelComplete: "Niveau terminé !",
        levelFailed: "Niveau échoué",
        tryAgain: "Réessayer",
        coverage: "Couverture",
        time: "Temps",
        rating: "Note",
        nextLevel: "Niveau suivant",
        replay: "Rejouer",
        pressContinue: "Appuyez sur Espace ou touchez pour continuer",
        pauseTitle: "⏸️ Pause",
        restart: "Recommencer",
        quit: "Quitter",
        menu: "Menu",
        target: "Objectif",
        tutorial: "Tutoriel",
        timeUsed: "Temps utilisé",
        excellent: "Excellent !",
        good: "Bien joué !",
        passed: "Réussi",
        bonusFuel: "Carburant utilisé",
        bonusFlawless: "Premier essai",
        bonusSpeed: "Temps",
        bonusWinch: "Utilisations du treuil",
        bonusExplore: "Routes explorées",
        retry: "Réessayer",
        gameComplete: "Jeu terminé !",
        viewCredits: "Voir les crédits",
        creditsTitle: "Félicitations !",
        creditsSubtitle: "Vous avez maîtrisé Les Aiguilles Blanches",
        playAgain: "Rejouer",
        skipCredits: "Appuyez sur une touche pour passer",
        
        // Tutorial - Step by step
        tutorialName: "Tutoriel - Premiers Pas",
        tutorialTask: "Apprenez les bases du damage",
        tutorialIntro: "Bienvenue aux Aiguilles Blanches !",
        tutorialWelcome: "🏔️ Bienvenue, recrue ! Je suis Jean-Pierre, chef dameur. Je vais t'apprendre le métier.",
        tutorialControls: "🎮 Pour bouger la dameuse, utilise {keys} ou les flèches ↑↓←→.",
        tutorialControlsTouch: "🎮 Pour bouger la dameuse, utilise le D-pad ◀▲▼▶ à gauche.",
        tutorialControlsGamepad: "🎮 Pour bouger la dameuse, utilise le stick gauche ou le D-pad.",
        tutorialMove: "➡️ Allez, essaie ! Déplace-toi sur la piste — toute la neige blanche doit être damée.",
        tutorialGroomIntro: "✅ Bien joué ! Maintenant, passons au damage.",
        tutorialGroomAction: "❄️ Maintiens {groomKey} en roulant pour damer la neige. Tu verras, ça se fait presque tout seul.",
        tutorialGroomActionTouch: "❄️ Maintiens le bouton ❄️ à droite en roulant pour damer la neige.",
        tutorialGroomActionGamepad: "❄️ Maintiens {groomKey} en roulant pour damer la neige. Tu verras, ça se fait presque tout seul.",
        tutorialCoverage: "📊 Tu vois ? La neige devient plus lisse ! Continue à damer la piste.",
        tutorialHUD: "📈 Regarde le tableau de bord en haut : la barre rouge c'est ton carburant, la verte ton endurance, et la blanche ta couverture. Le chrono tourne !",
        tutorialGoal: "🎯 Il faut damer au moins 40% de la piste avant l'ouverture. Les skieurs arrivent bientôt !",
        tutorialFuel: "⛽ Attention, rouler consomme du carburant. En mission, passe à la station-service !",
        tutorialComplete: "🏆 Bravo ! Tu maîtrises les bases. Prêt pour ta première vraie mission sur la Piste Verte ?",
        
        // Levels
        level_marmottesName: "Piste Verte - Les Marmottes",
        level_marmottesTask: "Damez la piste débutant",
        level_chamoisName: "Piste Bleue - Le Chamois",
        level_chamoisTask: "Damez efficacement avant l'ouverture",
        level_airZoneName: "Snowpark - Air Zone",
        level_airZoneTask: "Préparez les modules de freestyle",
        level_aigleName: "Piste Rouge - L'Aigle",
        level_aigleTask: "Damez le terrain pentu, gérez le carburant",
        level_glacierName: "Piste Rouge - Le Glacier",
        level_glacierTask: "Apprenez à utiliser le treuil en pente",
        level_tubeName: "Half-pipe - Le Tube",
        level_tubeTask: "Entretenez le half-pipe pour la compétition",
        level_verticaleName: "Piste Noire - La Verticale",
        level_verticaleTask: "Opération nocturne avec treuil",
        level_colDangereuxName: "Zone Avalanche - Col Dangereux",
        level_colDangereuxTask: "Préparez la zone à haut risque",
        level_tempeteName: "Tempête - Récupération",
        level_tempeteTask: "Dégagez les pistes après la tempête",
        level_coupeDesAiguillesName: "Coupe des Aiguilles - Finale FIS",
        level_coupeDesAiguillesTask: "Préparez toutes les pistes pour la compétition",
        
        // Hazards
        cliffFall: "⚠️ ATTENTION ! Vous êtes tombé dans le ravin ! Mission échouée.",
        fuelEmpty: "⛽ PANNE SÈCHE ! Plus une goutte de diesel...",
        avalancheZone: "ZONE AVALANCHE",
        riskLevelHigh: "FORT",
        avalancheWarning: "⚠️ DANGER ! Le manteau neigeux est instable ! Sortez de la zone !",
        avalancheTrigger: "🏔️💨 AVALANCHE DÉCLENCHÉE ! Évacuation impossible !",
        steepWarning: "⚠️ PENTE RAIDE ! Utilisez le treuil (SHIFT) ou vous allez glisser !",
        tumble: "🔄 TONNEAU ! La dameuse a basculé sur la pente !",
        
        // Taunts - Tumble/Rollover (emphasize winch lesson, expensive damage)
        tauntTumble1: "Le treuil, c'est pas décoratif. C'est pour les pentes comme ça.",
        tauntTumble2: "Thierry contemple les dégâts. Il ne dit rien. C'est pire.",
        tauntTumble3: "Jean-Pierre t'avait montré comment s'ancrer. Tu dormais ?",
        tauntTumble4: "Une PistenBully, ça coûte 400 000€. Enfin, ça coûtait.",
        tauntTumble5: "La pente te semblait gérable ? La dameuse n'était pas d'accord.",
        
        // Taunts - Avalanche (emphasize danger, respect for mountain)
        tauntAvalanche1: "La montagne pardonne rarement. Elle n'a pas pardonné.",
        tauntAvalanche2: "Le bulletin Météo France disait risque 4. Tu l'as lu ?",
        tauntAvalanche3: "Les pisteurs retrouveront la dameuse au printemps. Peut-être.",
        tauntAvalanche4: "Marie écoute l'alerte radio. Elle sait déjà que c'est toi.",
        tauntAvalanche5: "Le PIDA avait sécurisé le secteur. Tu l'as désécurisé.",
        
        // Dialogues
        jeanPierreIntro: "Bienvenue aux Aiguilles Blanches, petit ! Je suis Jean-Pierre, le chef dameur.",
        level_chamoisIntro: "Bien joué hier, petit ! Jean-Pierre t'envoie sur la bleue. Montre-moi que t'es pas qu'un dameur de verte.",
        level_airZoneIntro: "Salut ! C'est Émilie. Le snowpark a besoin d'amour — les riders comptent sur nous. Précision !",
        level_aigleIntro: "L'Aigle, c'est du sérieux. Surveille ton carburant. Les chemins de dameuse permettent de remonter la piste — repère les piquets jaunes et noirs.",
        level_glacierIntro: "Le Glacier, c'est raide. Thierry t'a préparé les ancrages. Appuie sur {winchKey} à côté d'un poteau pour accrocher le treuil — ça t'évitera de glisser.",
        level_glacierIntroTouch: "Le Glacier, c'est raide. Thierry t'a préparé les ancrages. Appuie sur le bouton treuil à côté d'un poteau pour t'accrocher — ça t'évitera de glisser.",
        level_tubeIntro: "Compétition demain ! Le half-pipe doit être impeccable.",
        level_verticaleIntro: "Opération de nuit sur La Verticale. Utilise le treuil.",
        level_colDangereuxIntro: "Attention, la zone avalanche est sensible. Sois prudent.",
        level_tempeteIntro: "La tempête est passée. Prends un vin chaud, ça va être long !",
        level_coupeDesAiguillesIntro: "C'est le grand soir. La FIS inspecte demain. Toutes les pistes doivent être parfaites — montre-moi ce que t'as appris.",
        marieWelcome: "Viens te réchauffer Chez Marie. Une bonne tartiflette !",
        
        // Changelog
        changelog_20260210_date: "10 février 2026",
        changelog_20260210: "🎵 Musique de piano procédurale\n🔊 Effets sonores moteur et environnement\n🗣️ Voix des personnages\n🔈 Réglages de volume",
        changelog_20260209_date: "9 février 2026",
        changelog_20260209: "🏔️ Écrans victoire/défaite alpins\n❄️ Neige de tempête sur les éléments\n🏆 Bonus sans faute\n🔊 Ambiances météo et faune",
        changelog_20260208_date: "8 février 2026",
        changelog_20260208: "📊 Nouveau tableau de bord\n🏔️ Le Glacier et Coupe des Aiguilles\n🦅 Faune alpine\n🎨 Portraits des personnages\n🎮 Navigation clavier/manette",
        changelog_20260207_date: "7 février 2026",
        changelog_20260207: "🎨 Interface rétro\n🎯 Objectifs bonus\n🕹️ Remappage boutons manette\n🎮 Navigation manette",
        changelog_20260206_date: "6 février 2026",
        changelog_20260206: "🛤️ Chemins de dameuse praticables\n🕹️ Joystick virtuel\n🌍 5 langues complètes",
        changelog_20260205_date: "5 février 2026",
        changelog_20260205: "🏔️ Falaises rocheuses\n🌙 Phares de nuit\n🔗 Mécanique de treuil\n⌨️ Navigation clavier",
        changelog_20260204_date: "4 février 2026",
        changelog_20260204: "🎮 Support manette\n📱 Contrôles tactiles\n💪 Endurance\n💾 Sauvegarde\n♿ Accessibilité",
        changelog_20260203_date: "3 février 2026",
        changelog_20260203: "🚜 Lancement : 9 niveaux, tutoriel\n❄️ Damage, carburant, avalanches\n🏆 Crédits et progression"
    },
    
    en: {
        subtitle: "Snow Groomer Simulation",
        startGame: "Start Game",
        resumeGame: "Resume",
        newGame: "New Game",
        continue: "Continue",
        settings: "Settings",
        controls: "Controls",
        changelog: "What's New",
        howToPlay: "How to Play",
        fullscreen: "Fullscreen",
        fullscreenHint: "Press F for fullscreen",
        exitFullscreen: "Exit Fullscreen",
        back: "Back",
        backToGame: "Back to Game",
        loading: "Loading...",
        madeIn: "Made with ❄️ in Savoie",
        on: "✓ ON",
        off: "✗ OFF",
        zoneClosed: "🚫 ZONE CLOSED",
        
        // Settings
        language: "Language",
        accessibility: "Accessibility",
        highContrast: "High Contrast",
        reducedMotion: "Reduced Motion",
        colorblindMode: "Colorblind",
        none: "None",
        deuteranopia: "Deutan.",
        protanopia: "Protan.",
        tritanopia: "Tritan.",
        uiScale: "UI Scale",
        move: "Move",
        moveUp: "Up",
        moveDown: "Down",
        moveLeft: "Left",
        moveRight: "Right",
        groom: "Groom",
        winch: "Winch",
        pause: "Pause",
        clickToRebind: "Click to rebind",
        pressKey: "Press a key...",
        pressGamepadButton: "Press a gamepad button...",
        gamepadButtons: "Gamepad Buttons",
        saved: "Saved!",
        resetControls: "Reset All",
        controlsReset: "Controls reset!",
        movementSensitivity: "Sensitivity",
        keyboardLayout: "Layout",
        customBindings: "Custom",
        gamepadSupported: "Gamepad OK",
        touchSupported: "Touch OK",
        noGamepadConnected: "No gamepad connected",

        // Audio
        audio: "Audio",
        masterVolume: "Master Volume",
        musicVolume: "Music",
        sfxVolume: "Sound Effects",
        voiceVolume: "Voice",
        ambienceVolume: "Ambience",
        mute: "Mute",
        
        // How to Play hints
        howToPlayMove: "{keys} or Arrows to move",
        howToPlayMoveTouch: "Use the virtual D-pad",
        howToPlayMoveGamepad: "Left stick or D-pad to move",
        howToPlayMoveHybrid: "{keys}/Arrows or touch D-pad",
        howToPlayGroom: "{groomKey} to groom snow",
        howToPlayGroomTouch: "Tap ❄️ to groom",
        howToPlayGroomGamepad: "to groom snow",
        howToPlayGroomHybrid: "{groomKey} or tap ❄️ to groom",
        howToPlayFuel: "Watch your fuel and stamina!",
        
        // Winch
        winchAttached: "🔗 Winch attached! Hold {winchKey} for assistance.",
        winchActive: "WINCH",
        winchHint: "Press {winchKey} near a numbered anchor post to use winch",
        winchHintTouch: "Hold 🔗 for winch",
        accessPath: "Service Road",
        toPiste: "To the piste",
        
        // Taunts - Cliff falls (emphasize the dramatic fall, insurance headaches, rescue hassle)
        tauntCliff1: "9 tons into the ravine. Insurance will love this.",
        tauntCliff2: "Jean-Pierre said 'not too close to the edge!' Remember?",
        tauntCliff3: "Ski patrol is coming down with ropes. Again.",
        tauntCliff4: "Marie cancels your raclette reservation for tonight.",
        tauntCliff5: "Thierry is already calculating repair costs...",
        
        // Taunts - Fuel empty (emphasize planning failure, team disappointment)
        tauntFuel1: "The gauge was on red for 10 minutes. What were you looking at?",
        tauntFuel2: "Émilie wrote 'REFUEL' in capital letters on the board.",
        tauntFuel3: "Even diesel has limits. So do you, apparently.",
        tauntFuel4: "Jean-Pierre sighs. He's sending Thierry with a jerry can.",
        tauntFuel5: "Sun's rising. Piste isn't groomed. Skiers are arriving.",
        
        // Taunts - Time limit (emphasize consequences for skiers and competition)
        tauntTime1: "First chairlift in 3... 2... 1... Missed it.",
        tauntTime2: "Skiers discover your piste. Bumpy. Icy. Magnificent.",
        tauntTime3: "Jean-Pierre looks at his watch, then at you, then his watch.",
        tauntTime4: "FIS is asking why the slalom is on soup.",
        tauntTime5: "You hear ski instructors explaining to clients why it's 'not their fault'.",
        
        paused: "Paused",
        resume: "Resume",
        quitToMenu: "Quit to Menu",
        levelComplete: "Level Complete!",
        levelFailed: "Level Failed",
        tryAgain: "Try Again",
        coverage: "Coverage",
        time: "Time",
        rating: "Rating",
        nextLevel: "Next Level",
        replay: "Replay",
        pressContinue: "Press Space or tap to continue",
        pauseTitle: "⏸️ Paused",
        restart: "Restart",
        quit: "Quit",
        menu: "Menu",
        target: "Target",
        tutorial: "Tutorial",
        timeUsed: "Time Used",
        excellent: "Excellent!",
        good: "Well done!",
        passed: "Passed",
        bonusFuel: "Fuel used",
        bonusFlawless: "First try",
        bonusSpeed: "Time",
        bonusWinch: "Winch uses",
        bonusExplore: "Roads explored",
        retry: "Retry",
        gameComplete: "Game Complete!",
        viewCredits: "View Credits",
        creditsTitle: "Congratulations!",
        creditsSubtitle: "You have mastered Les Aiguilles Blanches",
        playAgain: "Play Again",
        skipCredits: "Press any key to skip",
        
        // Tutorial - Full walkthrough
        tutorialName: "Tutorial - First Steps",
        tutorialTask: "Learn grooming basics",
        tutorialIntro: "Welcome to Les Aiguilles Blanches!",
        tutorialWelcome: "🏔️ Welcome, rookie! I'm Jean-Pierre, head groomer. I'll teach you the trade.",
        tutorialControls: "🎮 To move the groomer, use {keys} or the arrow keys ↑↓←→.",
        tutorialControlsTouch: "🎮 To move the groomer, use the D-pad ◀▲▼▶ on the left.",
        tutorialControlsGamepad: "🎮 To move the groomer, use the left stick or D-pad.",
        tutorialMove: "➡️ Go on, try it! Move around the piste — all the white snow needs grooming.",
        tutorialGroomIntro: "✅ Nice! Now let's learn to groom.",
        tutorialGroomAction: "❄️ Hold {groomKey} while driving to groom the snow. It'll smooth right out.",
        tutorialGroomActionTouch: "❄️ Hold the ❄️ button on the right while driving to groom the snow.",
        tutorialGroomActionGamepad: "❄️ Hold {groomKey} while driving to groom the snow. It'll smooth right out.",
        tutorialCoverage: "📊 See? The snow becomes smoother! Keep grooming the piste.",
        tutorialHUD: "📈 Check the dashboard up top: the red bar is fuel, green is stamina, white is coverage. The clock's ticking!",
        tutorialGoal: "🎯 You need to groom at least 40% of the piste before opening. Skiers are coming!",
        tutorialFuel: "⛽ Careful — driving burns fuel. On missions, stop by the fuel station.",
        tutorialComplete: "🏆 Well done! You've mastered the basics. Ready for your first real mission on the Green Piste?",
        
        level_marmottesName: "Green Piste - Les Marmottes",
        level_marmottesTask: "Groom the beginner slope",
        level_chamoisName: "Blue Piste - Le Chamois",
        level_chamoisTask: "Groom efficiently before opening",
        level_airZoneName: "Snowpark - Air Zone",
        level_airZoneTask: "Prepare freestyle features",
        level_aigleName: "Red Piste - L'Aigle",
        level_aigleTask: "Groom steep terrain, manage fuel",
        level_glacierName: "Red Piste - Le Glacier",
        level_glacierTask: "Learn to use the winch on steep slopes",
        level_tubeName: "Half-pipe - Le Tube",
        level_tubeTask: "Maintain the half-pipe for competition",
        level_verticaleName: "Black Piste - La Verticale",
        level_verticaleTask: "Night operation with winch",
        level_colDangereuxName: "Avalanche Zone - Col Dangereux",
        level_colDangereuxTask: "Prepare the high-risk zone",
        level_tempeteName: "Storm - Recovery",
        level_tempeteTask: "Clear pistes after the storm",
        level_coupeDesAiguillesName: "Coupe des Aiguilles - FIS Finale",
        level_coupeDesAiguillesTask: "Prepare all pistes for the competition",
        
        // Hazards
        cliffFall: "⚠️ WARNING! You fell off the cliff! Mission failed.",
        fuelEmpty: "⛽ OUT OF FUEL! Not a drop of diesel left...",
        avalancheZone: "AVALANCHE ZONE",
        riskLevelHigh: "HIGH",
        avalancheWarning: "⚠️ DANGER! Snowpack is unstable! Leave the zone!",
        avalancheTrigger: "🏔️💨 AVALANCHE TRIGGERED! No escape!",
        steepWarning: "⚠️ STEEP SLOPE! Use the winch (SHIFT) or you'll slide!",
        tumble: "🔄 ROLLOVER! The groomer tumbled on the slope!",
        
        // Taunts - Tumble/Rollover (emphasize winch lesson, expensive damage)
        tauntTumble1: "The winch isn't decorative. It's for slopes like this.",
        tauntTumble2: "Thierry stares at the damage. Says nothing. That's worse.",
        tauntTumble3: "Jean-Pierre showed you how to anchor. Were you asleep?",
        tauntTumble4: "A PistenBully costs €400,000. Well, it did.",
        tauntTumble5: "The slope seemed manageable? The groomer disagreed.",
        
        // Taunts - Avalanche (emphasize danger, respect for mountain)
        tauntAvalanche1: "The mountain rarely forgives. It didn't forgive.",
        tauntAvalanche2: "Météo France said risk level 4. Did you read it?",
        tauntAvalanche3: "Ski patrol will find the groomer in spring. Maybe.",
        tauntAvalanche4: "Marie hears the radio alert. She already knows it's you.",
        tauntAvalanche5: "The avalanche team had secured that sector. You un-secured it.",
        
        jeanPierreIntro: "Welcome to Les Aiguilles Blanches! I'm Jean-Pierre, head groomer.",
        level_chamoisIntro: "Nice work yesterday! Jean-Pierre's sending you to the blue run. Show him you're more than a green-run groomer.",
        level_airZoneIntro: "Hey! It's Émilie. The snowpark needs some love — riders are counting on us. Precision is key!",
        level_aigleIntro: "L'Aigle is serious. Watch your fuel. Cat tracks let you drive back up — look for the amber and black striped poles.",
        level_glacierIntro: "Le Glacier is steep. Thierry set up the anchors. Press {winchKey} near a post to attach the winch — it'll keep you from sliding.",
        level_glacierIntroTouch: "Le Glacier is steep. Thierry set up the anchors. Tap the winch button near a post to attach — it'll keep you from sliding.",
        level_tubeIntro: "Competition tomorrow! Half-pipe must be spotless.",
        level_verticaleIntro: "Night ops on La Verticale. Use the winch.",
        level_colDangereuxIntro: "Careful, avalanche zone is sensitive today.",
        level_tempeteIntro: "Storm's passed. Grab a vin chaud — this'll take a while!",
        level_coupeDesAiguillesIntro: "This is the big night. FIS inspects tomorrow. Every piste must be perfect — show me what you've learned.",
        marieWelcome: "Come warm up at Chez Marie. A good tartiflette!",
        
        // Changelog
        changelog_20260210_date: "February 10, 2026",
        changelog_20260210: "🎵 Procedural piano music\n🔊 Engine and environment sound effects\n🗣️ Character voices\n🔈 Volume settings",
        changelog_20260209_date: "February 9, 2026",
        changelog_20260209: "🏔️ Alpine win/fail screens\n❄️ Storm snow accumulation\n🏆 Flawless bonus\n🔊 Weather and wildlife ambience",
        changelog_20260208_date: "February 8, 2026",
        changelog_20260208: "📊 Redesigned dashboard\n🏔️ Le Glacier and Coupe des Aiguilles\n🦅 Alpine wildlife\n🎨 Character portraits\n🎮 Keyboard & gamepad navigation",
        changelog_20260207_date: "February 7, 2026",
        changelog_20260207: "🎨 Retro UI\n🎯 Bonus objectives\n🕹️ Gamepad button rebinding\n🎮 Gamepad menu navigation",
        changelog_20260206_date: "February 6, 2026",
        changelog_20260206: "🛤️ Traversable cat tracks\n🕹️ Virtual joystick\n🌍 5 complete languages",
        changelog_20260205_date: "February 5, 2026",
        changelog_20260205: "🏔️ Rocky cliffs\n🌙 Night headlights\n🔗 Winch mechanics\n⌨️ Keyboard navigation",
        changelog_20260204_date: "February 4, 2026",
        changelog_20260204: "🎮 Gamepad support\n📱 Touch controls\n💪 Stamina\n💾 Save progress\n♿ Accessibility",
        changelog_20260203_date: "February 3, 2026",
        changelog_20260203: "🚜 Launch: 9 levels, tutorial\n❄️ Grooming, fuel, avalanches\n🏆 Credits and progression"
    },
    
    de: {
        subtitle: "Pistenraupen-Simulation",
        startGame: "Spiel starten",
        resumeGame: "Fortsetzen",
        newGame: "Neues Spiel",
        continue: "Fortfahren",
        settings: "Einstellungen",
        controls: "Steuerung",
        changelog: "Neuigkeiten",
        howToPlay: "Anleitung",
        howToPlayMove: "{keys} oder Pfeiltasten bewegen",
        howToPlayMoveHybrid: "{keys}/Pfeile oder Touch-D-pad",
        howToPlayGroom: "{groomKey} zum Präparieren",
        howToPlayGroomHybrid: "{groomKey} oder ❄️ tippen",
        fullscreen: "Vollbild",
        fullscreenHint: "F drücken für Vollbild",
        exitFullscreen: "Vollbild beenden",
        back: "Zurück",
        backToGame: "Zurück zum Spiel",
        loading: "Laden...",
        madeIn: "Mit ❄️ in Savoyen gemacht",
        on: "✓ AN",
        off: "✗ AUS",
        zoneClosed: "🚫 ZONE GESPERRT",
        
        // Settings
        language: "Sprache",
        accessibility: "Barrierefreiheit",
        highContrast: "Hoher Kontrast",
        reducedMotion: "Weniger Bewegung",
        colorblindMode: "Farbenblind",
        none: "Keine",
        deuteranopia: "Deuteran.",
        protanopia: "Protan.",
        tritanopia: "Tritan.",
        move: "Bewegen",
        moveUp: "Hoch",
        moveDown: "Runter",
        moveLeft: "Links",
        moveRight: "Rechts",
        groom: "Präparieren",
        winch: "Winde",
        pause: "Pause",
        clickToRebind: "Klicken zum Ändern",
        pressKey: "Taste drücken...",
        pressGamepadButton: "Gamepad-Taste drücken...",
        gamepadButtons: "Gamepad-Tasten",
        saved: "Gespeichert!",
        resetControls: "Zurücksetzen",
        controlsReset: "Steuerung zurückgesetzt!",
        movementSensitivity: "Empfindlichkeit",
        keyboardLayout: "Tastaturlayout",
        customBindings: "Benutzerdefiniert",
        gamepadSupported: "Gamepad OK",
        touchSupported: "Touch OK",
        noGamepadConnected: "Kein Gamepad verbunden",

        // Audio
        audio: "Audio",
        masterVolume: "Gesamtlautstärke",
        musicVolume: "Musik",
        sfxVolume: "Soundeffekte",
        voiceVolume: "Stimme",
        ambienceVolume: "Ambiente",
        mute: "Stumm",
        
        // How to Play hints
        howToPlayMoveTouch: "Verwende das virtuelle D-Pad",
        howToPlayMoveGamepad: "Stick oder D-Pad zum Bewegen",
        howToPlayGroomTouch: "Tippe ❄️ zum Präparieren",
        howToPlayGroomGamepad: "zum Präparieren",
        howToPlayFuel: "Achte auf Kraftstoff und Ausdauer!",
        
        // Winch
        winchAttached: "🔗 Winde befestigt! Halte {winchKey} für Unterstützung.",
        winchActive: "WINDE",
        winchHint: "Drücke {winchKey} bei einem nummerierten Ankerpfosten für die Winde",
        winchHintTouch: "Halte 🔗 für die Winde",
        accessPath: "Zufahrtsweg",
        toPiste: "Zur Piste",
        
        // Game
        paused: "Pausiert",
        resume: "Fortsetzen",
        quitToMenu: "Zum Menü",
        levelComplete: "Level geschafft!",
        levelFailed: "Level fehlgeschlagen",
        tryAgain: "Nochmal",
        coverage: "Abdeckung",
        time: "Zeit",
        target: "Ziel",
        rating: "Bewertung",
        nextLevel: "Nächstes Level",
        replay: "Wiederholen",
        pressContinue: "Leertaste oder tippen zum Fortfahren",
        pauseTitle: "⏸️ Pause",
        restart: "Neustart",
        quit: "Beenden",
        menu: "Menü",
        tutorial: "Tutorial",
        timeUsed: "Benötigte Zeit",
        excellent: "Ausgezeichnet!",
        good: "Gut gemacht!",
        passed: "Geschafft",
        bonusFuel: "Treibstoff verbraucht",
        bonusFlawless: "Erster Versuch",
        bonusSpeed: "Zeit",
        bonusWinch: "Windeneinsätze",
        bonusExplore: "Wege erkundet",
        retry: "Wiederholen",
        gameComplete: "Spiel beendet!",
        viewCredits: "Credits anzeigen",
        creditsTitle: "Glückwunsch!",
        creditsSubtitle: "Du hast Les Aiguilles Blanches gemeistert",
        playAgain: "Nochmal spielen",
        skipCredits: "Taste drücken zum Überspringen",
        fr: "Französisch",
        
        // Levels - Tutorial step by step
        tutorialName: "Tutorial - Erste Schritte",
        tutorialTask: "Grundlagen lernen",
        tutorialIntro: "Willkommen in Les Aiguilles Blanches!",
        tutorialWelcome: "🏔️ Willkommen, Neuling! Ich bin Jean-Pierre, Chefpräparierer. Ich bringe dir das Handwerk bei.",
        tutorialControls: "🎮 Um den Pistenbully zu bewegen, nutze {keys} oder die Pfeiltasten ↑↓←→.",
        tutorialControlsTouch: "🎮 Um den Pistenbully zu bewegen, nutze das D-Pad ◀▲▼▶ links.",
        tutorialControlsGamepad: "🎮 Um den Pistenbully zu bewegen, nutze den linken Stick oder das D-Pad.",
        tutorialMove: "➡️ Los, probier's! Fahr über die Piste — der weiße Schnee muss präpariert werden.",
        tutorialGroomIntro: "✅ Gut gemacht! Jetzt lernen wir das Präparieren.",
        tutorialGroomAction: "❄️ Halte {groomKey} beim Fahren, um den Schnee zu präparieren. Du wirst sehen, das geht wie von selbst!",
        tutorialGroomActionTouch: "❄️ Halte den ❄️ Knopf rechts beim Fahren, um den Schnee zu präparieren.",
        tutorialGroomActionGamepad: "❄️ Halte {groomKey} beim Fahren, um den Schnee zu präparieren. Du wirst sehen, das geht wie von selbst!",
        tutorialCoverage: "📊 Siehst du? Der Schnee wird glatter! Präpariere weiter!",
        tutorialHUD: "📈 Schau oben aufs Dashboard: der rote Balken ist Kraftstoff, der grüne Ausdauer, der weiße die Abdeckung. Die Uhr läuft!",
        tutorialGoal: "🎯 Du musst mindestens 40% der Piste vor der Öffnung präparieren. Die Skifahrer kommen bald!",
        tutorialFuel: "⛽ Vorsicht, Fahren verbraucht Kraftstoff. Bei Missionen fahr zur Tankstelle!",
        tutorialComplete: "🏆 Super! Du beherrschst die Grundlagen. Bereit für deine erste Mission auf der Grünen Piste?",
        level_marmottesName: "Grüne Piste - Les Marmottes",
        level_marmottesTask: "Präpariere die Anfängerpiste",
        level_chamoisName: "Blaue Piste - Le Chamois",
        level_chamoisTask: "Präpariere effizient vor der Öffnung",
        level_airZoneName: "Snowpark - Air Zone",
        level_airZoneTask: "Bereite die Freestyle-Module vor",
        level_aigleName: "Rote Piste - L'Aigle",
        level_aigleTask: "Steiles Terrain, Kraftstoff managen",
        level_glacierName: "Rote Piste - Le Glacier",
        level_glacierTask: "Lerne die Winde am Steilhang zu benutzen",
        level_tubeName: "Halfpipe - Le Tube",
        level_tubeTask: "Halfpipe für den Wettkampf vorbereiten",
        level_verticaleName: "Schwarze Piste - La Verticale",
        level_verticaleTask: "Nachteinsatz mit Winde",
        level_colDangereuxName: "Lawinenzone - Col Dangereux",
        level_colDangereuxTask: "Hochrisikogebiet vorbereiten",
        level_tempeteName: "Sturm - Bergung",
        level_tempeteTask: "Pisten nach dem Sturm räumen",
        level_coupeDesAiguillesName: "Coupe des Aiguilles - FIS Finale",
        level_coupeDesAiguillesTask: "Alle Pisten für den Wettkampf vorbereiten",
        
        // Hazards
        cliffFall: "⚠️ ACHTUNG! Sie sind in die Schlucht gefallen! Mission gescheitert.",
        fuelEmpty: "⛽ LEER! Kein Tropfen Diesel mehr...",
        avalancheZone: "LAWINENZONE",
        riskLevelHigh: "HOCH",
        avalancheWarning: "⚠️ GEFAHR! Instabile Schneedecke! Verlasse die Zone!",
        avalancheTrigger: "🏔️💨 LAWINE AUSGELÖST! Keine Flucht möglich!",
        steepWarning: "⚠️ STEILER HANG! Benutze die Winde (SHIFT) oder du rutschst ab!",
        tumble: "🔄 ÜBERSCHLAG! Der Pistenbully ist umgekippt!",
        
        // Dialogues
        jeanPierreIntro: "Willkommen in Les Aiguilles Blanches, Kleiner! Ich bin Jean-Pierre, der Pistenchef.",
        level_chamoisIntro: "Gut gemacht gestern, Kleiner! Jean-Pierre schickt dich auf die Blaue. Zeig ihm, dass du mehr als ein Anfänger-Pistenraupe bist.",
        level_airZoneIntro: "Hey! Hier ist Émilie. Der Snowpark braucht Liebe — die Rider zählen auf uns. Präzision!",
        level_aigleIntro: "L'Aigle ist ernst. Achte auf den Kraftstoff. Die Ziehwege führen zurück nach oben — achte auf die gelb-schwarz gestreiften Stangen.",
        level_glacierIntro: "Le Glacier ist steil. Thierry hat die Anker vorbereitet. Drücke {winchKey} neben einem Pfosten, um die Winde einzuhaken — damit rutscht du nicht ab.",
        level_glacierIntroTouch: "Le Glacier ist steil. Thierry hat die Anker vorbereitet. Tippe auf den Winden-Button neben einem Pfosten — damit rutscht du nicht ab.",
        level_tubeIntro: "Morgen ist Wettkampf! Die Halfpipe muss perfekt sein.",
        level_verticaleIntro: "Nachteinsatz auf La Verticale. Benutze die Winde.",
        level_colDangereuxIntro: "Achtung, die Lawinenzone ist empfindlich. Sei vorsichtig.",
        level_tempeteIntro: "Der Sturm ist vorbei. Nimm einen Glühwein, das wird lang!",
        level_coupeDesAiguillesIntro: "Das ist die große Nacht. Die FIS inspiziert morgen. Jede Piste muss perfekt sein — zeig mir, was du gelernt hast.",
        marieWelcome: "Komm dich aufwärmen bei Marie. Eine leckere Tartiflette!",
        
        // Changelog
        changelog_20260210_date: "10. Februar 2026",
        changelog_20260210: "🎵 Prozedurale Klaviermusik\n🔊 Motor- und Umgebungsgeräusche\n🗣️ Charakterstimmen\n🔈 Lautstärkeeinstellungen",
        changelog_20260209_date: "9. Februar 2026",
        changelog_20260209: "🏔️ Alpine Sieg-/Niederlagenbilder\n❄️ Schneeakkumulation bei Sturm\n🏆 Fehlerlos-Bonus\n🔊 Wetter- und Tiergeräusche",
        changelog_20260208_date: "8. Februar 2026",
        changelog_20260208: "📊 Neues Dashboard\n🏔️ Le Glacier und Coupe des Aiguilles\n🦅 Alpine Tierwelt\n🎨 Charakterporträts\n🎮 Tastatur- & Gamepad-Navigation",
        changelog_20260207_date: "7. Februar 2026",
        changelog_20260207: "🎨 Retro-UI\n🎯 Bonusziele\n🕹️ Gamepad-Tastenbelegung\n🎮 Gamepad-Navigation",
        changelog_20260206_date: "6. Februar 2026",
        changelog_20260206: "🛤️ Befahrbare Pistenraupenspuren\n🕹️ Virtueller Joystick\n🌍 5 vollständige Sprachen",
        changelog_20260205_date: "5. Februar 2026",
        changelog_20260205: "🏔️ Felsige Klippen\n🌙 Nachtscheinwerfer\n🔗 Windenmechanik\n⌨️ Tastaturnavigation",
        changelog_20260204_date: "4. Februar 2026",
        changelog_20260204: "🎮 Gamepad-Unterstützung\n📱 Touch-Steuerung\n💪 Ausdauer\n💾 Speicherung\n♿ Barrierefreiheit",
        changelog_20260203_date: "3. Februar 2026",
        changelog_20260203: "🚜 Start: 9 Level, Tutorial\n❄️ Präparieren, Kraftstoff, Lawinen\n🏆 Credits und Fortschritt",

        // Taunts - Cliff
        tauntCliff1: "9 Tonnen in der Schlucht. Die Versicherung wird begeistert sein.",
        tauntCliff2: "Jean-Pierre sagte: 'Nicht zu nah am Rand!' Erinnerst du dich?",
        tauntCliff3: "Die Bergwacht kommt mit Seilen. Wieder.",
        tauntCliff4: "Marie storniert deine Raclette-Reservierung für heute Abend.",
        tauntCliff5: "Thierry rechnet bereits die Reparaturkosten...",
        // Taunts - Fuel
        tauntFuel1: "Die Anzeige war 10 Minuten lang auf Rot. Was hast du angeschaut?",
        tauntFuel2: "Émilie hatte 'TANKEN' in Großbuchstaben geschrieben.",
        tauntFuel3: "Selbst Diesel hat Grenzen. Du offenbar auch.",
        tauntFuel4: "Jean-Pierre seufzt. Er schickt Thierry mit einem Kanister.",
        tauntFuel5: "Die Sonne geht auf. Die Piste ist nicht präpariert. Die Skifahrer kommen.",
        // Taunts - Time
        tauntTime1: "Erster Sessellift in 3... 2... 1... Verpasst.",
        tauntTime2: "Skifahrer entdecken deine Piste. Buckelig. Vereist. Toll.",
        tauntTime3: "Jean-Pierre schaut auf seine Uhr, dann auf dich, dann auf seine Uhr.",
        tauntTime4: "Die FIS fragt, warum der Slalom auf Suppe stattfindet.",
        tauntTime5: "Du hörst Skilehrer den Gästen erklären, dass es 'nicht ihre Schuld' ist.",
        // Taunts - Tumble
        tauntTumble1: "Die Winde ist nicht zur Dekoration da.",
        tauntTumble2: "Thierry starrt auf den Schaden. Sagt nichts. Das ist schlimmer.",
        tauntTumble3: "Jean-Pierre hat dir gezeigt, wie man ankert. Hast du geschlafen?",
        tauntTumble4: "Ein PistenBully kostet 400.000€. Naja, kostete.",
        tauntTumble5: "Der Hang schien machbar? Die Raupe war anderer Meinung.",
        // Taunts - Avalanche
        tauntAvalanche1: "Der Berg verzeiht selten. Er hat nicht verziehen.",
        tauntAvalanche2: "Météo France sagte Risikostufe 4. Hast du gelesen?",
        tauntAvalanche3: "Die Bergwacht findet die Raupe im Frühling. Vielleicht.",
        tauntAvalanche4: "Marie hört den Funkalarm. Sie weiß schon, dass du es warst.",
        tauntAvalanche5: "Das Lawinenteam hatte den Sektor gesichert. Du hast ihn ent-sichert."
    },
    
    it: {
        subtitle: "Simulazione Gatto delle Nevi",
        startGame: "Inizia",
        resumeGame: "Riprendi",
        newGame: "Nuova Partita",
        continue: "Continua",
        settings: "Impostazioni",
        controls: "Comandi",
        changelog: "Novità",
        howToPlay: "Come Giocare",
        howToPlayMove: "{keys} o Frecce per muoversi",
        howToPlayMoveHybrid: "{keys}/Frecce o D-pad touch",
        howToPlayGroom: "{groomKey} per preparare",
        howToPlayGroomHybrid: "{groomKey} o tocca ❄️",
        fullscreen: "Schermo intero",
        fullscreenHint: "Premi F per schermo intero",
        exitFullscreen: "Esci schermo intero",
        back: "Indietro",
        backToGame: "Torna al gioco",
        loading: "Caricamento...",
        madeIn: "Fatto con ❄️ in Savoia",
        on: "✓ SÌ",
        off: "✗ NO",
        zoneClosed: "🚫 ZONA CHIUSA",
        
        // Settings
        language: "Lingua",
        accessibility: "Accessibilità",
        highContrast: "Alto Contrasto",
        reducedMotion: "Meno Movimento",
        colorblindMode: "Daltonismo",
        none: "Nessuno",
        deuteranopia: "Deuteran.",
        protanopia: "Protan.",
        tritanopia: "Tritan.",
        move: "Muovi",
        moveUp: "Su",
        moveDown: "Giù",
        moveLeft: "Sinistra",
        moveRight: "Destra",
        groom: "Battipista",
        winch: "Verricello",
        pause: "Pausa",
        clickToRebind: "Clicca per modificare",
        pressKey: "Premi un tasto...",
        pressGamepadButton: "Premi un pulsante del gamepad...",
        gamepadButtons: "Pulsanti gamepad",
        saved: "Salvato!",
        resetControls: "Ripristina",
        controlsReset: "Comandi ripristinati!",
        movementSensitivity: "Sensibilità",
        keyboardLayout: "Layout tastiera",
        customBindings: "Personalizzato",
        gamepadSupported: "Gamepad OK",
        touchSupported: "Touch OK",
        noGamepadConnected: "Nessun gamepad connesso",

        // Audio
        audio: "Audio",
        masterVolume: "Volume principale",
        musicVolume: "Musica",
        sfxVolume: "Effetti sonori",
        voiceVolume: "Voce",
        ambienceVolume: "Ambiente",
        mute: "Muto",
        
        // How to Play hints
        howToPlayMoveTouch: "Usa il D-pad virtuale",
        howToPlayMoveGamepad: "Stick o D-pad per muoversi",
        howToPlayGroomTouch: "Tocca ❄️ per preparare",
        howToPlayGroomGamepad: "per preparare la neve",
        howToPlayFuel: "Controlla carburante e resistenza!",
        
        // Winch
        winchAttached: "🔗 Verricello agganciato! Tieni {winchKey} per assistenza.",
        winchActive: "VERRICELLO",
        winchHint: "Premi {winchKey} vicino a un paletto di ancoraggio numerato per il verricello",
        winchHintTouch: "Tieni 🔗 per il verricello",
        accessPath: "Strada di servizio",
        toPiste: "Verso la pista",
        
        // Game
        paused: "Pausa",
        resume: "Riprendi",
        quitToMenu: "Torna al Menu",
        levelComplete: "Livello completato!",
        levelFailed: "Livello fallito",
        tryAgain: "Riprova",
        coverage: "Copertura",
        time: "Tempo",
        target: "Obiettivo",
        rating: "Voto",
        nextLevel: "Prossimo livello",
        replay: "Rigiocare",
        pressContinue: "Premi Spazio o tocca per continuare",
        pauseTitle: "⏸️ Pausa",
        restart: "Ricomincia",
        quit: "Esci",
        menu: "Menu",
        tutorial: "Tutorial",
        timeUsed: "Tempo impiegato",
        excellent: "Eccellente!",
        good: "Ben fatto!",
        passed: "Superato",
        bonusFuel: "Carburante usato",
        bonusFlawless: "Primo tentativo",
        bonusSpeed: "Tempo",
        bonusWinch: "Usi del verricello",
        bonusExplore: "Strade esplorate",
        retry: "Riprova",
        gameComplete: "Gioco completato!",
        viewCredits: "Vedi crediti",
        creditsTitle: "Complimenti!",
        creditsSubtitle: "Hai padroneggiato Les Aiguilles Blanches",
        playAgain: "Rigiocare",
        skipCredits: "Premi un tasto per saltare",
        fr: "Francese",
        
        // Levels - Tutorial step by step
        tutorialName: "Tutorial - Primi Passi",
        tutorialTask: "Impara le basi",
        tutorialIntro: "Benvenuto a Les Aiguilles Blanches!",
        tutorialWelcome: "🏔️ Benvenuto, novellino! Sono Jean-Pierre, capo gattista. Ti insegnerò il mestiere.",
        tutorialControls: "🎮 Per muovere il gatto delle nevi, usa {keys} o le frecce ↑↓←→.",
        tutorialControlsTouch: "🎮 Per muoverti, usa il D-pad ◀▲▼▶ a sinistra.",
        tutorialControlsGamepad: "🎮 Per muoverti, usa lo stick sinistro o il D-pad.",
        tutorialMove: "➡️ Dai, prova! Muoviti sulla pista — tutta la neve bianca va battuta.",
        tutorialGroomIntro: "✅ Ottimo! Ora impariamo a battere la neve.",
        tutorialGroomAction: "❄️ Tieni {groomKey} mentre guidi per battere la neve. Vedrai, viene subito bella liscia!",
        tutorialGroomActionTouch: "❄️ Tieni il pulsante ❄️ a destra mentre guidi per battere la neve.",
        tutorialGroomActionGamepad: "❄️ Tieni {groomKey} mentre guidi per battere la neve. Vedrai, viene subito bella liscia!",
        tutorialCoverage: "📊 Vedi? La neve diventa più liscia! Continua a battere!",
        tutorialHUD: "📈 Guarda il cruscotto in alto: la barra rossa è il carburante, la verde la resistenza, la bianca è la copertura. Il tempo scorre!",
        tutorialGoal: "🎯 Devi battere almeno il 40% della pista prima dell'apertura. Gli sciatori stanno arrivando!",
        tutorialFuel: "⛽ Attento, guidare consuma carburante. Durante le missioni, fai un salto alla stazione di servizio!",
        tutorialComplete: "🏆 Bravo! Hai imparato le basi. Pronto per la tua prima missione sulla Pista Verde?",
        level_marmottesName: "Pista Verde - Les Marmottes",
        level_marmottesTask: "Prepara la pista principianti",
        level_chamoisName: "Pista Blu - Le Chamois",
        level_chamoisTask: "Prepara prima dell'apertura",
        level_airZoneName: "Snowpark - Air Zone",
        level_airZoneTask: "Prepara i moduli freestyle",
        level_aigleName: "Pista Rossa - L'Aigle",
        level_aigleTask: "Terreno ripido, gestisci il carburante",
        level_glacierName: "Pista Rossa - Le Glacier",
        level_glacierTask: "Impara ad usare il verricello in pendenza",
        level_tubeName: "Halfpipe - Le Tube",
        level_tubeTask: "Prepara l'halfpipe per la gara",
        level_verticaleName: "Pista Nera - La Verticale",
        level_verticaleTask: "Operazione notturna con verricello",
        level_colDangereuxName: "Zona Valanghe - Col Dangereux",
        level_colDangereuxTask: "Prepara la zona ad alto rischio",
        level_tempeteName: "Tempesta - Recupero",
        level_tempeteTask: "Libera le piste dopo la tempesta",
        level_coupeDesAiguillesName: "Coupe des Aiguilles - Finale FIS",
        level_coupeDesAiguillesTask: "Prepara tutte le piste per la competizione",
        
        // Hazards
        cliffFall: "⚠️ ATTENZIONE! Sei caduto nel dirupo! Missione fallita.",
        fuelEmpty: "⛽ SERBATOIO VUOTO! Neanche una goccia di diesel...",
        avalancheZone: "ZONA VALANGHE",
        riskLevelHigh: "ALTO",
        avalancheWarning: "⚠️ PERICOLO! Manto nevoso instabile! Esci dalla zona!",
        avalancheTrigger: "🏔️💨 VALANGA INNESCATA! Impossibile evacuare!",
        steepWarning: "⚠️ PENDIO RIPIDO! Usa il verricello (SHIFT) o scivolerai!",
        tumble: "🔄 RIBALTAMENTO! Il gatto delle nevi si è rovesciato!",
        
        // Dialogues
        jeanPierreIntro: "Benvenuto a Les Aiguilles Blanches, piccolo! Sono Jean-Pierre, il capo gattista.",
        level_chamoisIntro: "Ben fatto ieri, piccolo! Jean-Pierre ti manda sulla blu. Faglielo vedere che non sei solo un gattista da verde.",
        level_airZoneIntro: "Ciao! Sono Émilie. Lo snowpark ha bisogno di cure — i rider contano su di noi. Precisione!",
        level_aigleIntro: "L'Aigle è roba seria. Occhio al carburante. I tracciati battipista permettono di risalire — cerca i pali a strisce gialle e nere.",
        level_glacierIntro: "Le Glacier è ripido. Thierry ha preparato gli ancoraggi. Premi {winchKey} vicino a un paletto per agganciare il verricello — eviterai di scivolare.",
        level_glacierIntroTouch: "Le Glacier è ripido. Thierry ha preparato gli ancoraggi. Tocca il pulsante verricello vicino a un paletto per agganciarti — eviterai di scivolare.",
        level_tubeIntro: "Domani c'è la gara! L'halfpipe deve essere perfetto.",
        level_verticaleIntro: "Operazione notturna su La Verticale. Usa il verricello.",
        level_colDangereuxIntro: "Attenzione, la zona valanghe è sensibile. Fai attenzione.",
        level_tempeteIntro: "La tempesta è passata. Prendi un vin brulé, sarà lunga!",
        level_coupeDesAiguillesIntro: "È la grande notte. La FIS ispeziona domani. Ogni pista deve essere perfetta — mostrami cosa hai imparato.",
        marieWelcome: "Vieni a scaldarti da Marie. Una bella tartiflette!",
        
        // Changelog
        changelog_20260210_date: "10 febbraio 2026",
        changelog_20260210: "🎵 Musica di pianoforte procedurale\n🔊 Effetti sonori motore e ambiente\n🗣️ Voci dei personaggi\n🔈 Impostazioni volume",
        changelog_20260209_date: "9 febbraio 2026",
        changelog_20260209: "🏔️ Schermate vittoria/sconfitta alpine\n❄️ Accumulo neve da tempesta\n🏆 Bonus senza errori\n🔊 Suoni meteo e fauna",
        changelog_20260208_date: "8 febbraio 2026",
        changelog_20260208: "📊 Nuovo cruscotto\n🏔️ Le Glacier e Coupe des Aiguilles\n🦅 Fauna alpina\n🎨 Ritratti dei personaggi\n🎮 Navigazione tastiera e gamepad",
        changelog_20260207_date: "7 febbraio 2026",
        changelog_20260207: "🎨 UI retro\n🎯 Obiettivi bonus\n🕹️ Rimappatura tasti gamepad\n🎮 Navigazione gamepad",
        changelog_20260206_date: "6 febbraio 2026",
        changelog_20260206: "🛤️ Tracciati battipista percorribili\n🕹️ Joystick virtuale\n🌍 5 lingue complete",
        changelog_20260205_date: "5 febbraio 2026",
        changelog_20260205: "🏔️ Dirupi rocciosi\n🌙 Fari notturni\n🔗 Meccanica verricello\n⌨️ Navigazione tastiera",
        changelog_20260204_date: "4 febbraio 2026",
        changelog_20260204: "🎮 Supporto gamepad\n📱 Controlli touch\n💪 Resistenza\n💾 Salvataggio\n♿ Accessibilità",
        changelog_20260203_date: "3 febbraio 2026",
        changelog_20260203: "🚜 Lancio: 9 livelli, tutorial\n❄️ Preparazione, carburante, valanghe\n🏆 Crediti e progressione",

        // Taunts - Cliff
        tauntCliff1: "9 tonnellate nel burrone. L'assicurazione sarà entusiasta.",
        tauntCliff2: "Jean-Pierre aveva detto: 'Non troppo vicino al bordo!' Ricordi?",
        tauntCliff3: "Il soccorso alpino arriva con le corde. Di nuovo.",
        tauntCliff4: "Marie cancella la tua prenotazione per la raclette di stasera.",
        tauntCliff5: "Thierry sta già calcolando i costi di riparazione...",
        // Taunts - Fuel
        tauntFuel1: "L'indicatore era rosso da 10 minuti. Cosa guardavi?",
        tauntFuel2: "Émilie aveva scritto 'FARE RIFORNIMENTO' in maiuscolo.",
        tauntFuel3: "Anche il diesel ha i suoi limiti. Tu pure, a quanto pare.",
        tauntFuel4: "Jean-Pierre sospira. Manda Thierry con una tanica.",
        tauntFuel5: "Il sole sorge. La pista non è preparata. Gli sciatori stanno arrivando.",
        // Taunts - Time
        tauntTime1: "Prima seggiovia tra 3... 2... 1... Persa.",
        tauntTime2: "Gli sciatori scoprono la tua pista. Dissestata. Ghiacciata. Magnifica.",
        tauntTime3: "Jean-Pierre guarda l'orologio, poi te, poi di nuovo l'orologio.",
        tauntTime4: "La FIS chiede perché lo slalom è su una zuppa.",
        tauntTime5: "Senti i maestri di sci spiegare ai clienti che 'non è colpa loro'.",
        // Taunts - Tumble
        tauntTumble1: "Il verricello non è decorativo. È per pendii come questo.",
        tauntTumble2: "Thierry fissa i danni. Non dice niente. È peggio.",
        tauntTumble3: "Jean-Pierre ti ha mostrato come ancorarti. Dormivi?",
        tauntTumble4: "Un PistenBully costa 400.000€. Beh, costava.",
        tauntTumble5: "Il pendio sembrava gestibile? Il gatto non era d'accordo.",
        // Taunts - Avalanche
        tauntAvalanche1: "La montagna perdona raramente. Non ha perdonato.",
        tauntAvalanche2: "Météo France diceva rischio 4. L'hai letto?",
        tauntAvalanche3: "Il soccorso troverà il gatto in primavera. Forse.",
        tauntAvalanche4: "Marie sente l'allarme radio. Sa già che sei tu.",
        tauntAvalanche5: "La squadra valanghe aveva messo in sicurezza il settore. Tu l'hai de-sicurato."
    },
    
    es: {
        subtitle: "Simulación de Pisapistas",
        startGame: "Empezar",
        resumeGame: "Continuar Partida",
        newGame: "Nueva Partida",
        continue: "Continuar",
        settings: "Ajustes",
        controls: "Controles",
        changelog: "Novedades",
        howToPlay: "Cómo Jugar",
        howToPlayMove: "{keys} o Flechas para mover",
        howToPlayMoveHybrid: "{keys}/Flechas o D-pad táctil",
        howToPlayGroom: "{groomKey} para preparar",
        howToPlayGroomHybrid: "{groomKey} o toca ❄️",
        fullscreen: "Pantalla completa",
        fullscreenHint: "Pulsa F para pantalla completa",
        exitFullscreen: "Salir pantalla completa",
        back: "Volver",
        backToGame: "Volver al juego",
        loading: "Cargando...",
        madeIn: "Hecho con ❄️ en Saboya",
        on: "✓ SÍ",
        off: "✗ NO",
        zoneClosed: "🚫 ZONA CERRADA",
        
        // Settings
        language: "Idioma",
        accessibility: "Accesibilidad",
        highContrast: "Alto Contraste",
        reducedMotion: "Menos Movimiento",
        colorblindMode: "Daltonismo",
        none: "Ninguno",
        deuteranopia: "Deuteran.",
        protanopia: "Protan.",
        tritanopia: "Tritan.",
        move: "Mover",
        moveUp: "Arriba",
        moveDown: "Abajo",
        moveLeft: "Izquierda",
        moveRight: "Derecha",
        groom: "Pisar",
        winch: "Cabrestante",
        pause: "Pausa",
        clickToRebind: "Clic para cambiar",
        pressKey: "Pulsa una tecla...",
        pressGamepadButton: "Pulsa un botón del mando...",
        gamepadButtons: "Botones del mando",
        saved: "¡Guardado!",
        resetControls: "Restablecer",
        controlsReset: "¡Controles restablecidos!",
        movementSensitivity: "Sensibilidad",
        keyboardLayout: "Distribución",
        customBindings: "Personalizado",
        gamepadSupported: "Gamepad OK",
        touchSupported: "Táctil OK",
        noGamepadConnected: "Ningún gamepad conectado",

        // Audio
        audio: "Audio",
        masterVolume: "Volumen general",
        musicVolume: "Música",
        sfxVolume: "Efectos de sonido",
        voiceVolume: "Voz",
        ambienceVolume: "Ambiente",
        mute: "Silenciar",
        
        // How to Play hints
        howToPlayMoveTouch: "Usa el D-pad virtual",
        howToPlayMoveGamepad: "Stick o D-pad para mover",
        howToPlayGroomTouch: "Toca ❄️ para preparar",
        howToPlayGroomGamepad: "para preparar la nieve",
        howToPlayFuel: "¡Vigila el combustible y la resistencia!",
        
        // Winch
        winchAttached: "🔗 ¡Cabrestante enganchado! Mantén {winchKey} para asistencia.",
        winchActive: "CABRESTANTE",
        winchHint: "Pulsa {winchKey} cerca de un poste de anclaje numerado para usar el cabrestante",
        winchHintTouch: "Mantén 🔗 para el cabrestante",
        accessPath: "Camino de servicio",
        toPiste: "Hacia la pista",
        
        // Game
        paused: "Pausado",
        resume: "Reanudar",
        quitToMenu: "Volver al Menú",
        levelComplete: "¡Nivel completado!",
        levelFailed: "Nivel fallido",
        tryAgain: "Reintentar",
        coverage: "Cobertura",
        time: "Tiempo",
        target: "Objetivo",
        rating: "Puntuación",
        nextLevel: "Siguiente nivel",
        replay: "Rejugar",
        pressContinue: "Pulsa Espacio o toca para continuar",
        pauseTitle: "⏸️ Pausa",
        restart: "Reiniciar",
        quit: "Salir",
        menu: "Menú",
        tutorial: "Tutorial",
        timeUsed: "Tiempo usado",
        excellent: "¡Excelente!",
        good: "¡Bien hecho!",
        passed: "Aprobado",
        bonusFuel: "Combustible usado",
        bonusFlawless: "Primer intento",
        bonusSpeed: "Tiempo",
        bonusWinch: "Usos del cabrestante",
        bonusExplore: "Caminos explorados",
        retry: "Reintentar",
        gameComplete: "¡Juego completado!",
        viewCredits: "Ver créditos",
        creditsTitle: "¡Felicidades!",
        creditsSubtitle: "Has dominado Les Aiguilles Blanches",
        playAgain: "Jugar de nuevo",
        skipCredits: "Pulsa una tecla para saltar",
        fr: "Francés",
        
        // Levels - Tutorial step by step
        tutorialName: "Tutorial - Primeros Pasos",
        tutorialTask: "Aprende lo básico",
        tutorialIntro: "¡Bienvenido a Les Aiguilles Blanches!",
        tutorialWelcome: "🏔️ ¡Bienvenido, novato! Soy Jean-Pierre, jefe pisador. Te enseñaré el oficio.",
        tutorialControls: "🎮 Para mover la pisapistas, usa {keys} o las flechas ↑↓←→.",
        tutorialControlsTouch: "🎮 Para moverte, usa el D-pad ◀▲▼▶ a la izquierda.",
        tutorialControlsGamepad: "🎮 Para moverte, usa el stick izquierdo o el D-pad.",
        tutorialMove: "➡️ Venga, prueba. Muévete por la pista — hay que pisar toda la nieve blanca.",
        tutorialGroomIntro: "✅ ¡Genial! Ahora aprendamos a pisar la nieve.",
        tutorialGroomAction: "❄️ Mantén {groomKey} mientras conduces para pisar la nieve. Ya verás, queda como una alfombra.",
        tutorialGroomActionTouch: "❄️ Mantén el botón ❄️ a la derecha mientras conduces para pisar la nieve.",
        tutorialGroomActionGamepad: "❄️ Mantén {groomKey} mientras conduces para pisar la nieve. Ya verás, queda como una alfombra.",
        tutorialCoverage: "📊 ¿Ves? ¡La nieve se vuelve más lisa! ¡Sigue pisando!",
        tutorialHUD: "📈 Mira el panel arriba: la barra roja es combustible, la verde resistencia, la blanca cobertura. ¡El reloj corre!",
        tutorialGoal: "🎯 Hay que pisar al menos el 40% de la pista antes de abrir. ¡Los esquiadores llegan pronto!",
        tutorialFuel: "⛽ Cuidado, conducir gasta combustible. ¡En misiones, pásate por la gasolinera!",
        tutorialComplete: "🏆 ¡Bravo! Dominas lo básico. ¿Listo para tu primera misión en la Pista Verde?",
        level_marmottesName: "Pista Verde - Les Marmottes",
        level_marmottesTask: "Prepara la pista de principiantes",
        level_chamoisName: "Pista Azul - Le Chamois",
        level_chamoisTask: "Prepara antes de la apertura",
        level_airZoneName: "Snowpark - Air Zone",
        level_airZoneTask: "Prepara los módulos de freestyle",
        level_aigleName: "Pista Roja - L'Aigle",
        level_aigleTask: "Terreno empinado, gestiona el combustible",
        level_glacierName: "Pista Roja - Le Glacier",
        level_glacierTask: "Aprende a usar el cabrestante en pendiente",
        level_tubeName: "Halfpipe - Le Tube",
        level_tubeTask: "Prepara el halfpipe para la competición",
        level_verticaleName: "Pista Negra - La Verticale",
        level_verticaleTask: "Operación nocturna con cabrestante",
        level_colDangereuxName: "Zona de Avalanchas - Col Dangereux",
        level_colDangereuxTask: "Prepara la zona de alto riesgo",
        level_tempeteName: "Tormenta - Recuperación",
        level_tempeteTask: "Despeja las pistas tras la tormenta",
        level_coupeDesAiguillesName: "Coupe des Aiguilles - Final FIS",
        level_coupeDesAiguillesTask: "Prepara todas las pistas para la competición",
        
        // Hazards
        cliffFall: "⚠️ ¡CUIDADO! ¡Has caído al precipicio! Misión fallida.",
        fuelEmpty: "⛽ ¡SIN COMBUSTIBLE! Ni una gota de diésel...",
        avalancheZone: "ZONA DE AVALANCHAS",
        riskLevelHigh: "ALTO",
        avalancheWarning: "⚠️ ¡PELIGRO! ¡Manto de nieve inestable! ¡Sal de la zona!",
        avalancheTrigger: "🏔️💨 ¡AVALANCHA DESENCADENADA! ¡Evacuación imposible!",
        steepWarning: "⚠️ ¡PENDIENTE EMPINADA! ¡Usa el cabrestante (SHIFT) o resbalarás!",
        tumble: "🔄 ¡VUELCO! ¡La máquina ha volcado en la pendiente!",
        
        // Dialogues
        jeanPierreIntro: "¡Bienvenido a Les Aiguilles Blanches, pequeño! Soy Jean-Pierre, el Jefe de pistas.",
        level_chamoisIntro: "¡Bien hecho ayer, pequeño! Jean-Pierre te envía a la azul. Demuéstrale que no eres solo un pisapistas de verde.",
        level_airZoneIntro: "¡Hola! Soy Émilie. El snowpark necesita cariño — los riders cuentan con nosotros. ¡Precisión!",
        level_aigleIntro: "L'Aigle es serio. Vigila el combustible. Los caminos de pisapistas permiten subir — busca los postes con rayas amarillas y negras.",
        level_glacierIntro: "Le Glacier es empinado. Thierry preparó los anclajes. Pulsa {winchKey} junto a un poste para enganchar el cabrestante — evitarás resbalar.",
        level_glacierIntroTouch: "Le Glacier es empinado. Thierry preparó los anclajes. Toca el botón de cabrestante junto a un poste para engancharte — evitarás resbalar.",
        level_tubeIntro: "¡Mañana hay competición! El halfpipe debe estar perfecto.",
        level_verticaleIntro: "Operación nocturna en La Verticale. Usa el cabrestante.",
        level_colDangereuxIntro: "Cuidado, la zona de avalanchas es sensible. Ten cuidado.",
        level_tempeteIntro: "La tormenta ha pasado. ¡Toma un vino caliente, va a ser largo!",
        level_coupeDesAiguillesIntro: "Es la gran noche. La FIS inspecciona mañana. Cada pista debe ser perfecta — muéstrame lo que has aprendido.",
        marieWelcome: "Ven a calentarte a lo de Marie. ¡Una buena tartiflette!",
        
        // Changelog
        changelog_20260210_date: "10 de febrero de 2026",
        changelog_20260210: "🎵 Música de piano procedural\n🔊 Efectos de sonido motor y ambiente\n🗣️ Voces de personajes\n🔈 Ajustes de volumen",
        changelog_20260209_date: "9 de febrero de 2026",
        changelog_20260209: "🏔️ Pantallas victoria/derrota alpinas\n❄️ Acumulación de nieve en tormenta\n🏆 Bonus sin fallos\n🔊 Sonidos de clima y fauna",
        changelog_20260208_date: "8 de febrero de 2026",
        changelog_20260208: "📊 Nuevo panel de control\n🏔️ Le Glacier y Coupe des Aiguilles\n🦅 Fauna alpina\n🎨 Retratos de personajes\n🎮 Navegación con teclado y mando",
        changelog_20260207_date: "7 de febrero de 2026",
        changelog_20260207: "🎨 UI retro\n🎯 Objetivos bonus\n🕹️ Reasignación de botones\n🎮 Navegación con mando",
        changelog_20260206_date: "6 de febrero de 2026",
        changelog_20260206: "🛤️ Caminos de pisapistas transitables\n🕹️ Joystick virtual\n🌍 5 idiomas completos",
        changelog_20260205_date: "5 de febrero de 2026",
        changelog_20260205: "🏔️ Acantilados rocosos\n🌙 Faros nocturnos\n🔗 Mecánica cabrestante\n⌨️ Navegación teclado",
        changelog_20260204_date: "4 de febrero de 2026",
        changelog_20260204: "🎮 Soporte mando\n📱 Controles táctiles\n💪 Resistencia\n💾 Guardado\n♿ Accesibilidad",
        changelog_20260203_date: "3 de febrero de 2026",
        changelog_20260203: "🚜 Lanzamiento: 9 niveles, tutorial\n❄️ Preparación, combustible, avalanchas\n🏆 Créditos y progresión",

        // Taunts - Cliff
        tauntCliff1: "9 toneladas en el barranco. Al seguro le va a encantar.",
        tauntCliff2: "Jean-Pierre dijo: '¡No tan cerca del borde!' ¿Recuerdas?",
        tauntCliff3: "El equipo de rescate baja con cuerdas. Otra vez.",
        tauntCliff4: "Marie cancela tu reserva de raclette para esta noche.",
        tauntCliff5: "Thierry ya está calculando los costes de reparación...",
        // Taunts - Fuel
        tauntFuel1: "El indicador llevaba 10 minutos en rojo. ¿Qué mirabas?",
        tauntFuel2: "Émilie escribió 'REPOSTAR' en mayúsculas en la pizarra.",
        tauntFuel3: "Hasta el diésel tiene límites. Tú también, al parecer.",
        tauntFuel4: "Jean-Pierre suspira. Envía a Thierry con un bidón.",
        tauntFuel5: "Sale el sol. La pista no está preparada. Llegan los esquiadores.",
        // Taunts - Time
        tauntTime1: "Primer telesilla en 3... 2... 1... Perdido.",
        tauntTime2: "Los esquiadores descubren tu pista. Con baches. Helada. Magnífica.",
        tauntTime3: "Jean-Pierre mira su reloj, luego a ti, luego a su reloj.",
        tauntTime4: "La FIS pregunta por qué el slalom está sobre sopa.",
        tauntTime5: "Oyes a los monitores explicar a los clientes que 'no es culpa suya'.",
        // Taunts - Tumble
        tauntTumble1: "El cabrestante no es decorativo. Es para pendientes así.",
        tauntTumble2: "Thierry contempla los daños. No dice nada. Es peor.",
        tauntTumble3: "Jean-Pierre te enseñó cómo anclarte. ¿Estabas dormido?",
        tauntTumble4: "Una PistenBully cuesta 400.000€. Bueno, costaba.",
        tauntTumble5: "¿La pendiente parecía manejable? La máquina no estaba de acuerdo.",
        // Taunts - Avalanche
        tauntAvalanche1: "La montaña rara vez perdona. No perdonó.",
        tauntAvalanche2: "Météo France dijo nivel de riesgo 4. ¿Lo leíste?",
        tauntAvalanche3: "El rescate encontrará la máquina en primavera. Quizás.",
        tauntAvalanche4: "Marie oye la alerta por radio. Ya sabe que eres tú.",
        tauntAvalanche5: "El equipo de avalanchas había asegurado el sector. Tú lo des-aseguraste."
    }
};

export function setLanguage(lang: SupportedLanguage): void {
    if (TRANSLATIONS[lang]) {
        currentLang = lang;
        setString(STORAGE_KEYS.LANG, lang);
    }
}

export function getLanguage(): SupportedLanguage {
    return currentLang;
}

export function t(key: string): string {
    return TRANSLATIONS[currentLang]?.[key] || TRANSLATIONS['en']?.[key] || key;
}

export function detectLanguage(): SupportedLanguage {
    const saved = getString(STORAGE_KEYS.LANG);
    if (saved && saved in TRANSLATIONS) {
        return saved as SupportedLanguage;
    }
    const browserLang = navigator.language.split('-')[0];
    return browserLang in TRANSLATIONS ? browserLang as SupportedLanguage : 'fr';
}

export function getSavedLanguage(): SupportedLanguage {
    return detectLanguage();
}
