/**
 * Les Aiguilles Blanches - Localization
 * Multi-language support for Phaser 3 version
 */

import { STORAGE_KEYS } from './storageKeys';

export type SupportedLanguage = 'fr' | 'en' | 'de' | 'it' | 'es';

let currentLang: SupportedLanguage = 'fr';

export const TRANSLATIONS: Record<SupportedLanguage, Record<string, string>> = {
    fr: {
        // Menu
        subtitle: "Simulation de Damage",
        startGame: "Commencer",
        resumeGame: "Reprendre",
        newGame: "Nouvelle partie",
        continue: "Continuer",
        settings: "Paramètres",
        controls: "Contrôles",
        changelog: "Nouveautés",
        howToPlay: "Comment jouer",
        fullscreen: "Plein écran",
        exitFullscreen: "Quitter plein écran",
        back: "Retour",
        backToGame: "Retour au jeu",
        loading: "Chargement...",
        madeIn: "Fait avec ❄️ en Savoie",
        on: "✓ OUI",
        off: "✗ NON",
        zoneClosed: "🚫 ZONE FERMÉE",
        
        // Settings
        language: "Langue",
        accessibility: "Accessibilité",
        highContrast: "Contraste élevé",
        reducedMotion: "Mouvement réduit",
        colorblindMode: "Daltonisme",
        none: "Aucun",
        deuteranopia: "Deutér.",
        protanopia: "Protan.",
        tritanopia: "Tritan.",
        
        // Controls
        move: "Déplacer",
        moveUp: "Haut",
        moveDown: "Bas",
        moveLeft: "Gauche",
        moveRight: "Droite",
        groom: "Damer",
        winch: "Treuil",
        pause: "Pause",
        clickToRebind: "Cliquer pour modifier",
        pressKey: "Appuyez sur une touche...",
        pressGamepadButton: "Appuyez sur un bouton de manette...",
        gamepadButtons: "Boutons manette",
        saved: "Sauvegardé !",
        resetControls: "Réinitialiser",
        controlsReset: "Contrôles réinitialisés !",
        gamepadSupported: "Manette OK",
        touchSupported: "Tactile OK",
        keyboardLayout: "Disposition clavier",
        customBindings: "Personnalisé",
        noGamepadConnected: "Aucune manette connectée",
        
        // How to Play hints
        howToPlayMove: "{keys} ou Flèches pour se déplacer",
        howToPlayMoveTouch: "Utilisez le D-pad virtuel",
        howToPlayMoveGamepad: "Stick ou D-pad pour se déplacer",
        howToPlayMoveHybrid: "{keys}/Flèches ou D-pad tactile",
        howToPlayGroom: "{groomKey} pour damer la neige",
        howToPlayGroomTouch: "Touchez ❄️ pour damer",
        howToPlayGroomGamepad: "pour damer la neige",
        howToPlayGroomHybrid: "{groomKey} ou touchez ❄️ pour damer",
        howToPlayFuel: "Surveillez carburant et endurance !",
        
        // Winch
        winchAttached: "🔗 Treuil attaché ! Maintenir {winchKey} pour assistance.",
        winchActive: "TREUIL",
        winchHint: "Appuyez sur {winchKey} près d'un ancrage numéroté pour utiliser le treuil",
        winchHintTouch: "Maintenir 🔗 pour le treuil",
        accessPath: "Route de service",
        toPiste: "Vers la piste",
        
        // Taunts - Cliff falls (emphasize the dramatic fall, insurance headaches, rescue hassle)
        tauntCliff1: "9 tonnes dans le ravin. L'assurance va adorer.",
        tauntCliff2: "Jean-Pierre t'avait dit : 'Pas trop près du bord !' Tu te souviens ?",
        tauntCliff3: "Les pisteurs descendent avec les cordes. Encore.",
        tauntCliff4: "Marie annule ta réservation pour la raclette de ce soir.",
        tauntCliff5: "Thierry calcule déjà le coût des réparations...",
        
        // Taunts - Fuel empty (emphasize planning failure, team disappointment)
        tauntFuel1: "La jauge était sur rouge depuis 10 minutes. Tu regardais quoi ?",
        tauntFuel2: "Émilie t'avait pourtant mis 'FAIRE LE PLEIN' en majuscules.",
        tauntFuel3: "Même le diesel a ses limites. Toi aussi, apparemment.",
        tauntFuel4: "Jean-Pierre soupire. Il envoie Thierry avec un jerrican.",
        tauntFuel5: "Le soleil se lève. La piste n'est pas damée. Les skieurs arrivent.",
        
        // Taunts - Time limit (emphasize consequences for skiers and competition)
        tauntTime1: "Premier télésiège dans 3... 2... 1... Raté.",
        tauntTime2: "Les skieurs découvrent ta piste. Bosselée. Verglacée. Magnifique.",
        tauntTime3: "Jean-Pierre regarde sa montre, puis toi, puis sa montre.",
        tauntTime4: "La FIS demande pourquoi le slalom est sur de la soupe.",
        tauntTime5: "Tu entends les moniteurs ESF expliquer aux clients pourquoi c'est 'pas de ta faute'.",
        
        // Game
        paused: "Pause",
        resume: "Reprendre",
        quitToMenu: "Retour au menu",
        levelComplete: "Niveau terminé !",
        levelFailed: "Niveau échoué",
        tryAgain: "Réessayer",
        coverage: "Couverture",
        time: "Temps",
        rating: "Note",
        nextLevel: "Niveau suivant",
        replay: "Rejouer",
        pressContinue: "Appuyez sur Espace ou touchez pour continuer",
        pauseTitle: "⏸️ Pause",
        restart: "Recommencer",
        quit: "Quitter",
        menu: "Menu",
        target: "Objectif",
        tutorial: "Tutoriel",
        timeUsed: "Temps utilisé",
        excellent: "Excellent !",
        good: "Bien joué !",
        passed: "Réussi",
        bonusFuel: "Carburant utilisé",
        bonusNoTumble: "Aucune chute",
        bonusSpeed: "Temps",
        bonusWinch: "Utilisations du treuil",
        bonusExplore: "Routes explorées",
        retry: "Réessayer",
        gameComplete: "Jeu terminé !",
        viewCredits: "Voir les crédits",
        creditsTitle: "Félicitations !",
        creditsSubtitle: "Vous avez maîtrisé Les Aiguilles Blanches",
        playAgain: "Rejouer",
        skipCredits: "Appuyez sur une touche pour passer",
        
        // Tutorial - Step by step
        tutorialName: "Tutoriel - Premiers Pas",
        tutorialTask: "Apprenez les bases du damage",
        tutorialIntro: "Bienvenue aux Aiguilles Blanches !",
        tutorialWelcome: "🏔️ Bienvenue, recrue ! Je suis Jean-Pierre, chef dameur. Je vais t'apprendre le métier.",
        tutorialControls: "🎮 CONTRÔLES : Utilise {keys} ou les flèches ↑↓←→ pour déplacer la dameuse.",
        tutorialControlsTouch: "🎮 CONTRÔLES : Utilise le D-pad ◀▲▼▶ à gauche pour déplacer la dameuse.",
        tutorialControlsGamepad: "🎮 CONTRÔLES : Utilise le stick gauche ou D-pad pour déplacer la dameuse.",
        tutorialMove: "👆 ESSAIE : Déplace-toi sur la piste. La neige blanche doit être damée !",
        tutorialGroomIntro: "✅ Bien joué ! Maintenant, passons au damage.",
        tutorialGroomAction: "❄️ DAMER : Maintiens {groomKey} tout en te déplaçant pour transformer la neige en piste damée.",
        tutorialGroomActionTouch: "❄️ DAMER : Maintiens le bouton ❄️ à droite tout en te déplaçant pour damer la neige.",
        tutorialGroomActionGamepad: "❄️ DAMER : Maintiens {groomKey} tout en te déplaçant pour transformer la neige en piste damée.",
        tutorialCoverage: "📊 Tu vois ? La neige devient plus lisse ! Continue à damer la piste.",
        tutorialHUD: "📈 INTERFACE : En haut à gauche : ⛽ Carburant, 💪 Endurance, ❄️ Couverture. En haut à droite : ⏱️ Temps et 🎯 Objectif.",
        tutorialGoal: "🎯 OBJECTIF : Dame au moins 40% de la piste avant la fin du temps. Les skieurs arrivent bientôt !",
        tutorialFuel: "⛽ CARBURANT : Se déplacer consomme du carburant. En mission, visite la station-service !",
        tutorialComplete: "🏆 Bravo ! Tu maîtrises les bases. Prêt pour ta première vraie mission sur la Piste Verte ?",
        
        // Levels
        level1Name: "Piste Verte - Les Marmottes",
        level1Task: "Damez la piste débutant",
        level2Name: "Piste Bleue - Le Chamois",
        level2Task: "Damez efficacement avant l'ouverture",
        level3Name: "Snowpark - Air Zone",
        level3Task: "Préparez les modules de freestyle",
        level4Name: "Piste Rouge - L'Aigle",
        level4Task: "Damez le terrain pentu, gérez le carburant",
        level5Name: "Half-pipe - Le Tube",
        level5Task: "Entretenez le half-pipe pour la compétition",
        level6Name: "Piste Noire - La Verticale",
        level6Task: "Opération nocturne avec treuil",
        level7Name: "Zone Avalanche - Col Dangereux",
        level7Task: "Préparez la zone à haut risque",
        level8Name: "Tempête - Récupération",
        level8Task: "Dégagez les pistes après la tempête",
        
        // Hazards
        cliffFall: "⚠️ ATTENTION ! Vous êtes tombé dans le ravin ! Mission échouée.",
        fuelEmpty: "⛽ PANNE SÈCHE ! Plus une goutte de diesel...",
        avalancheZone: "ZONE AVALANCHE",
        riskLevelHigh: "FORT",
        avalancheWarning: "⚠️ DANGER ! Le manteau neigeux est instable ! Sortez de la zone !",
        avalancheTrigger: "🏔️💨 AVALANCHE DÉCLENCHÉE ! Évacuation impossible !",
        steepWarning: "⚠️ PENTE RAIDE ! Utilisez le treuil (SHIFT) ou vous allez glisser !",
        tumble: "🔄 TONNEAU ! La dameuse a basculé sur la pente !",
        
        // Taunts - Tumble/Rollover (emphasize winch lesson, expensive damage)
        tauntTumble1: "Le treuil, c'est pas décoratif. C'est pour les pentes comme ça.",
        tauntTumble2: "Thierry contemple les dégâts. Il ne dit rien. C'est pire.",
        tauntTumble3: "Jean-Pierre t'avait montré comment s'ancrer. Tu dormais ?",
        tauntTumble4: "Une PistenBully, ça coûte 400 000€. Enfin, ça coûtait.",
        tauntTumble5: "La pente te semblait gérable ? La dameuse n'était pas d'accord.",
        
        // Taunts - Avalanche (emphasize danger, respect for mountain)
        tauntAvalanche1: "La montagne pardonne rarement. Elle n'a pas pardonné.",
        tauntAvalanche2: "Le bulletin Météo France disait risque 4. Tu l'as lu ?",
        tauntAvalanche3: "Les pisteurs retrouveront la dameuse au printemps. Peut-être.",
        tauntAvalanche4: "Marie écoute l'alerte radio. Elle sait déjà que c'est toi.",
        tauntAvalanche5: "Le PIDA avait sécurisé le secteur. Tu l'as dé-sécurisé.",
        
        // Dialogues
        jeanPierreIntro: "Bienvenue aux Aiguilles Blanches, petit ! Je suis Jean-Pierre, le chef dameur.",
        level2Intro: "Bien joué hier ! Aujourd'hui, on passe à la piste bleue.",
        level3Intro: "Le snowpark a besoin d'amour. Précision !",
        level4Intro: "L'Aigle, c'est du sérieux. Surveille ton carburant. Les chemins de dameuse permettent de remonter la piste — repère les piquets jaunes et noirs.",
        level4WinchIntro: "Tu vas voir des ancrages numérotés sur les pentes raides. Appuie sur {winchKey} à côté pour accrocher le treuil — ça t'évitera de glisser.",
        level4WinchIntroTouch: "Tu vas voir des ancrages numérotés sur les pentes raides. Appuie sur le bouton treuil à côté pour t'accrocher — ça t'évitera de glisser.",
        level5Intro: "Compétition demain ! Le half-pipe doit être impeccable.",
        level6Intro: "Opération de nuit sur La Verticale. Utilise le treuil.",
        thierryWarning: "Attention, la zone avalanche est sensible. Soyez prudent.",
        level8Intro: "La tempête est passée. Prends un vin chaud, ça va être long !",
        marieWelcome: "Viens te réchauffer Chez Marie. Une bonne tartiflette !",
        
        // Changelog
        changelogDate5: "7 février 2026",
        changelogDay5: "🎨 Interface rétro : panneaux 3D, portraits, machine à écrire\n🏷️ Icônes texte (FUEL, STAM, WINCH) au lieu d'emojis\n🎯 Objectifs bonus par niveau\n🕹️ Remappage boutons manette\n🎮 Navigation manette dans tous les menus",
        changelogDate4: "6 février 2026",
        changelogDay4: "🛤️ Chemins de dameuse praticables\n🕹️ Joystick virtuel\n🌍 5 langues complètes",
        changelogDate3: "5 février 2026",
        changelogDay3: "🏔️ Falaises rocheuses\n🌙 Phares de nuit\n🔗 Mécanique de treuil\n⌨️ Navigation clavier",
        changelogDate2: "4 février 2026",
        changelogDay2: "🎮 Support manette\n📱 Contrôles tactiles\n💪 Endurance\n💾 Sauvegarde\n♿ Accessibilité",
        changelogDate1: "3 février 2026",
        changelogDay1: "🚜 Lancement : 9 niveaux, tutoriel\n❄️ Damage, carburant, avalanches\n🏆 Crédits et progression"
    },
    
    en: {
        subtitle: "Snow Groomer Simulation",
        startGame: "Start Game",
        resumeGame: "Resume",
        newGame: "New Game",
        continue: "Continue",
        settings: "Settings",
        controls: "Controls",
        changelog: "What's New",
        howToPlay: "How to Play",
        fullscreen: "Fullscreen",
        exitFullscreen: "Exit Fullscreen",
        back: "Back",
        backToGame: "Back to Game",
        loading: "Loading...",
        madeIn: "Made with ❄️ in Savoie",
        on: "✓ ON",
        off: "✗ OFF",
        zoneClosed: "🚫 ZONE CLOSED",
        
        // Settings
        language: "Language",
        accessibility: "Accessibility",
        highContrast: "High Contrast",
        reducedMotion: "Reduced Motion",
        colorblindMode: "Colorblind",
        none: "None",
        deuteranopia: "Deutan.",
        protanopia: "Protan.",
        tritanopia: "Tritan.",
        uiScale: "UI Scale",
        move: "Move",
        moveUp: "Up",
        moveDown: "Down",
        moveLeft: "Left",
        moveRight: "Right",
        groom: "Groom",
        winch: "Winch",
        pause: "Pause",
        clickToRebind: "Click to rebind",
        pressKey: "Press a key...",
        pressGamepadButton: "Press a gamepad button...",
        gamepadButtons: "Gamepad Buttons",
        saved: "Saved!",
        resetControls: "Reset All",
        controlsReset: "Controls reset!",
        keyboardLayout: "Layout",
        customBindings: "Custom",
        gamepadSupported: "Gamepad OK",
        touchSupported: "Touch OK",
        noGamepadConnected: "No gamepad connected",
        
        // How to Play hints
        howToPlayMove: "{keys} or Arrows to move",
        howToPlayMoveTouch: "Use the virtual D-pad",
        howToPlayMoveGamepad: "Left stick or D-pad to move",
        howToPlayMoveHybrid: "{keys}/Arrows or touch D-pad",
        howToPlayGroom: "{groomKey} to groom snow",
        howToPlayGroomTouch: "Tap ❄️ to groom",
        howToPlayGroomGamepad: "to groom snow",
        howToPlayGroomHybrid: "{groomKey} or tap ❄️ to groom",
        howToPlayFuel: "Watch your fuel and stamina!",
        
        // Winch
        winchAttached: "🔗 Winch attached! Hold {winchKey} for assistance.",
        winchActive: "WINCH",
        winchHint: "Press {winchKey} near a numbered anchor post to use winch",
        winchHintTouch: "Hold 🔗 for winch",
        accessPath: "Service Road",
        toPiste: "To the piste",
        
        // Taunts - Cliff falls (emphasize the dramatic fall, insurance headaches, rescue hassle)
        tauntCliff1: "9 tons into the ravine. Insurance will love this.",
        tauntCliff2: "Jean-Pierre said 'not too close to the edge!' Remember?",
        tauntCliff3: "Ski patrol is coming down with ropes. Again.",
        tauntCliff4: "Marie cancels your raclette reservation for tonight.",
        tauntCliff5: "Thierry is already calculating repair costs...",
        
        // Taunts - Fuel empty (emphasize planning failure, team disappointment)
        tauntFuel1: "The gauge was on red for 10 minutes. What were you looking at?",
        tauntFuel2: "Émilie wrote 'REFUEL' in capital letters on the board.",
        tauntFuel3: "Even diesel has limits. So do you, apparently.",
        tauntFuel4: "Jean-Pierre sighs. He's sending Thierry with a jerry can.",
        tauntFuel5: "Sun's rising. Piste isn't groomed. Skiers are arriving.",
        
        // Taunts - Time limit (emphasize consequences for skiers and competition)
        tauntTime1: "First chairlift in 3... 2... 1... Missed it.",
        tauntTime2: "Skiers discover your piste. Bumpy. Icy. Magnificent.",
        tauntTime3: "Jean-Pierre looks at his watch, then at you, then his watch.",
        tauntTime4: "FIS is asking why the slalom is on soup.",
        tauntTime5: "You hear ski instructors explaining to clients why it's 'not their fault'.",
        
        paused: "Paused",
        resume: "Resume",
        quitToMenu: "Quit to Menu",
        levelComplete: "Level Complete!",
        levelFailed: "Level Failed",
        tryAgain: "Try Again",
        coverage: "Coverage",
        time: "Time",
        rating: "Rating",
        nextLevel: "Next Level",
        replay: "Replay",
        pressContinue: "Press Space or tap to continue",
        pauseTitle: "⏸️ Paused",
        restart: "Restart",
        quit: "Quit",
        menu: "Menu",
        target: "Target",
        tutorial: "Tutorial",
        timeUsed: "Time Used",
        excellent: "Excellent!",
        good: "Well done!",
        passed: "Passed",
        bonusFuel: "Fuel used",
        bonusNoTumble: "No tumbles",
        bonusSpeed: "Time",
        bonusWinch: "Winch uses",
        bonusExplore: "Roads explored",
        retry: "Retry",
        gameComplete: "Game Complete!",
        viewCredits: "View Credits",
        creditsTitle: "Congratulations!",
        creditsSubtitle: "You have mastered Les Aiguilles Blanches",
        playAgain: "Play Again",
        skipCredits: "Press any key to skip",
        
        // Tutorial - Full walkthrough
        tutorialName: "Tutorial - First Steps",
        tutorialTask: "Learn grooming basics",
        tutorialIntro: "Welcome to Les Aiguilles Blanches!",
        tutorialWelcome: "🏔️ Welcome, rookie! I'm Jean-Pierre, head groomer. I'll teach you the trade.",
        tutorialControls: "🎮 CONTROLS: Use {keys} or arrow keys ↑↓←→ to move the groomer.",
        tutorialControlsTouch: "🎮 CONTROLS: Use the D-pad ◀▲▼▶ on the left to move the groomer.",
        tutorialControlsGamepad: "🎮 CONTROLS: Use the left stick or D-pad to move the groomer.",
        tutorialMove: "👆 TRY IT: Move around the piste. The white snow needs to be groomed!",
        tutorialGroomIntro: "✅ Nice! Now let's learn to groom.",
        tutorialGroomAction: "❄️ GROOMING: Hold {groomKey} while moving to transform snow into a smooth piste.",
        tutorialGroomActionTouch: "❄️ GROOMING: Hold the ❄️ button on the right while moving to groom the snow.",
        tutorialGroomActionGamepad: "❄️ GROOMING: Hold {groomKey} while moving to transform snow into a smooth piste.",
        tutorialCoverage: "📊 See? The snow becomes smoother! Keep grooming the piste.",
        tutorialHUD: "📈 HUD: Top-left: ⛽ Fuel, 💪 Stamina, ❄️ Coverage. Top-right: ⏱️ Time and 🎯 Target.",
        tutorialGoal: "🎯 GOAL: Groom at least 40% of the piste before time runs out. Skiers are coming!",
        tutorialFuel: "⛽ FUEL: Moving uses fuel. On missions, visit the fuel station!",
        tutorialComplete: "🏆 Well done! You've mastered the basics. Ready for your first real mission on the Green Piste?",
        
        level1Name: "Green Piste - Les Marmottes",
        level1Task: "Groom the beginner slope",
        level2Name: "Blue Piste - Le Chamois",
        level2Task: "Groom efficiently before opening",
        level3Name: "Snowpark - Air Zone",
        level3Task: "Prepare freestyle features",
        level4Name: "Red Piste - L'Aigle",
        level4Task: "Groom steep terrain, manage fuel",
        level5Name: "Half-pipe - Le Tube",
        level5Task: "Maintain the half-pipe",
        level6Name: "Black Piste - La Verticale",
        level6Task: "Night operation with winch",
        level7Name: "Avalanche Zone - Col Dangereux",
        level7Task: "Prepare the high-risk zone",
        level8Name: "Storm - Recovery",
        level8Task: "Clear pistes after the storm",
        
        // Hazards
        cliffFall: "⚠️ WARNING! You fell off the cliff! Mission failed.",
        fuelEmpty: "⛽ OUT OF FUEL! Not a drop of diesel left...",
        avalancheZone: "AVALANCHE ZONE",
        riskLevelHigh: "HIGH",
        avalancheWarning: "⚠️ DANGER! Snowpack is unstable! Leave the zone!",
        avalancheTrigger: "🏔️💨 AVALANCHE TRIGGERED! No escape!",
        steepWarning: "⚠️ STEEP SLOPE! Use the winch (SHIFT) or you'll slide!",
        tumble: "🔄 ROLLOVER! The groomer tumbled on the slope!",
        
        // Taunts - Tumble/Rollover (emphasize winch lesson, expensive damage)
        tauntTumble1: "The winch isn't decorative. It's for slopes like this.",
        tauntTumble2: "Thierry stares at the damage. Says nothing. That's worse.",
        tauntTumble3: "Jean-Pierre showed you how to anchor. Were you asleep?",
        tauntTumble4: "A PistenBully costs €400,000. Well, it did.",
        tauntTumble5: "The slope seemed manageable? The groomer disagreed.",
        
        // Taunts - Avalanche (emphasize danger, respect for mountain)
        tauntAvalanche1: "The mountain rarely forgives. It didn't forgive.",
        tauntAvalanche2: "Météo France said risk level 4. Did you read it?",
        tauntAvalanche3: "Ski patrol will find the groomer in spring. Maybe.",
        tauntAvalanche4: "Marie hears the radio alert. She already knows it's you.",
        tauntAvalanche5: "The avalanche team had secured that sector. You un-secured it.",
        
        jeanPierreIntro: "Welcome to Les Aiguilles Blanches! I'm Jean-Pierre, head groomer.",
        level2Intro: "Nice work! Today we tackle the blue run.",
        level3Intro: "The snowpark needs love. Precision is key!",
        level4Intro: "L'Aigle is serious. Watch your fuel. Cat tracks let you drive back up — look for the amber and black striped poles.",
        level4WinchIntro: "You'll see numbered anchor posts on steep slopes. Press {winchKey} nearby to attach the winch — it'll keep you from sliding.",
        level4WinchIntroTouch: "You'll see numbered anchor posts on steep slopes. Tap the winch button nearby to attach — it'll keep you from sliding.",
        level5Intro: "Competition tomorrow! Half-pipe must be spotless.",
        level6Intro: "Night ops on La Verticale. Use the winch.",
        thierryWarning: "Careful, avalanche zone is sensitive today.",
        level8Intro: "Storm's passed. Grab a vin chaud - this'll take a while!",
        marieWelcome: "Come warm up at Chez Marie. A good tartiflette!",
        
        // Changelog
        changelogDate5: "February 7, 2026",
        changelogDay5: "🎨 Retro UI: 3D panels, portraits, typewriter text\n🏷️ Text labels (FUEL, STAM, WINCH) replace emojis\n🎯 Bonus objectives per level\n🕹️ Gamepad button rebinding\n🎮 Full gamepad menu navigation",
        changelogDate4: "February 6, 2026",
        changelogDay4: "🛤️ Traversable cat tracks\n🕹️ Virtual joystick\n🌍 5 complete languages",
        changelogDate3: "February 5, 2026",
        changelogDay3: "🏔️ Rocky cliffs\n🌙 Night headlights\n🔗 Winch mechanics\n⌨️ Keyboard navigation",
        changelogDate2: "February 4, 2026",
        changelogDay2: "🎮 Gamepad support\n📱 Touch controls\n💪 Stamina\n💾 Save progress\n♿ Accessibility",
        changelogDate1: "February 3, 2026",
        changelogDay1: "🚜 Launch: 9 levels, tutorial\n❄️ Grooming, fuel, avalanches\n🏆 Credits and progression"
    },
    
    de: {
        subtitle: "Pistenraupe Simulation",
        startGame: "Spiel starten",
        resumeGame: "Fortsetzen",
        newGame: "Neues Spiel",
        continue: "Fortfahren",
        settings: "Einstellungen",
        controls: "Steuerung",
        changelog: "Neuigkeiten",
        howToPlay: "Anleitung",
        howToPlayMove: "{keys} oder Pfeiltasten bewegen",
        howToPlayMoveHybrid: "{keys}/Pfeile oder Touch-D-pad",
        howToPlayGroom: "{groomKey} zum Präparieren",
        howToPlayGroomHybrid: "{groomKey} oder ❄️ tippen",
        fullscreen: "Vollbild",
        exitFullscreen: "Vollbild beenden",
        back: "Zurück",
        backToGame: "Zurück zum Spiel",
        loading: "Laden...",
        madeIn: "Mit ❄️ in Savoyen gemacht",
        on: "✓ AN",
        off: "✗ AUS",
        zoneClosed: "🚫 ZONE GESPERRT",
        
        // Settings
        language: "Sprache",
        accessibility: "Barrierefreiheit",
        highContrast: "Hoher Kontrast",
        reducedMotion: "Weniger Bewegung",
        colorblindMode: "Farbenblind",
        none: "Keine",
        deuteranopia: "Deuteran.",
        protanopia: "Protan.",
        tritanopia: "Tritan.",
        move: "Bewegen",
        moveUp: "Hoch",
        moveDown: "Runter",
        moveLeft: "Links",
        moveRight: "Rechts",
        groom: "Präparieren",
        winch: "Winde",
        pause: "Pause",
        clickToRebind: "Klicken zum Ändern",
        pressKey: "Taste drücken...",
        pressGamepadButton: "Gamepad-Taste drücken...",
        gamepadButtons: "Gamepad-Tasten",
        saved: "Gespeichert!",
        resetControls: "Zurücksetzen",
        controlsReset: "Steuerung zurückgesetzt!",
        keyboardLayout: "Tastaturlayout",
        customBindings: "Benutzerdefiniert",
        gamepadSupported: "Gamepad OK",
        touchSupported: "Touch OK",
        noGamepadConnected: "Kein Gamepad verbunden",
        
        // How to Play hints
        howToPlayMoveTouch: "Verwende das virtuelle D-Pad",
        howToPlayMoveGamepad: "Stick oder D-Pad zum Bewegen",
        howToPlayGroomTouch: "Tippe ❄️ zum Präparieren",
        howToPlayGroomGamepad: "zum Präparieren",
        howToPlayFuel: "Achte auf Kraftstoff und Ausdauer!",
        
        // Winch
        winchAttached: "🔗 Winde befestigt! Halte {winchKey} für Unterstützung.",
        winchActive: "WINDE",
        winchHint: "Drücke {winchKey} bei einem nummerierten Ankerpfosten für die Winde",
        winchHintTouch: "Halte 🔗 für die Winde",
        accessPath: "Zufahrtsweg",
        toPiste: "Zur Piste",
        
        // Game
        paused: "Pausiert",
        resume: "Fortsetzen",
        quitToMenu: "Zum Menü",
        levelComplete: "Level geschafft!",
        levelFailed: "Level fehlgeschlagen",
        tryAgain: "Nochmal",
        coverage: "Abdeckung",
        time: "Zeit",
        target: "Ziel",
        rating: "Bewertung",
        nextLevel: "Nächstes Level",
        replay: "Wiederholen",
        pressContinue: "Leertaste oder tippen zum Fortfahren",
        pauseTitle: "⏸️ Pause",
        restart: "Neustart",
        quit: "Beenden",
        menu: "Menü",
        tutorial: "Tutorial",
        timeUsed: "Benötigte Zeit",
        excellent: "Ausgezeichnet!",
        good: "Gut gemacht!",
        passed: "Geschafft",
        bonusFuel: "Treibstoff verbraucht",
        bonusNoTumble: "Kein Sturz",
        bonusSpeed: "Zeit",
        bonusWinch: "Windeneinsätze",
        bonusExplore: "Wege erkundet",
        retry: "Wiederholen",
        gameComplete: "Spiel beendet!",
        viewCredits: "Credits anzeigen",
        creditsTitle: "Glückwunsch!",
        creditsSubtitle: "Du hast Les Aiguilles Blanches gemeistert",
        playAgain: "Nochmal spielen",
        skipCredits: "Taste drücken zum Überspringen",
        fr: "Französisch",
        
        // Levels - Tutorial step by step
        tutorialName: "Tutorial - Erste Schritte",
        tutorialTask: "Grundlagen lernen",
        tutorialIntro: "Willkommen in Les Aiguilles Blanches!",
        tutorialWelcome: "🏔️ Willkommen, Neuling! Ich bin Jean-Pierre, Chefpräparierer. Ich bringe dir das Handwerk bei.",
        tutorialControls: "🎮 STEUERUNG: Benutze {keys} oder Pfeiltasten ↑↓←→ um den Pistenbully zu bewegen.",
        tutorialControlsTouch: "🎮 STEUERUNG: Benutze das D-Pad ◀▲▼▶ links zum Bewegen.",
        tutorialControlsGamepad: "🎮 STEUERUNG: Linker Stick oder D-Pad zum Bewegen.",
        tutorialMove: "👆 PROBIER ES: Bewege dich auf der Piste. Der weiße Schnee muss präpariert werden!",
        tutorialGroomIntro: "✅ Gut gemacht! Jetzt lernen wir das Präparieren.",
        tutorialGroomAction: "❄️ PRÄPARIEREN: Halte {groomKey} während der Fahrt, um den Schnee zu glätten.",
        tutorialGroomActionTouch: "❄️ PRÄPARIEREN: Halte den ❄️ Knopf rechts zum Präparieren.",
        tutorialGroomActionGamepad: "❄️ PRÄPARIEREN: Halte {groomKey} während der Fahrt zum Präparieren.",
        tutorialCoverage: "📊 Siehst du? Der Schnee wird glatter! Präpariere weiter!",
        tutorialHUD: "📈 ANZEIGE: Oben links: ⛽ Kraftstoff, 💪 Ausdauer, ❄️ Abdeckung. Oben rechts: ⏱️ Zeit und 🎯 Ziel.",
        tutorialGoal: "🎯 ZIEL: Präpariere mindestens 40% der Piste vor Zeitablauf. Die Skifahrer kommen!",
        tutorialFuel: "⛽ KRAFTSTOFF: Fahren verbraucht Kraftstoff. Bei Missionen zur Tankstelle!",
        tutorialComplete: "🏆 Super! Du beherrschst die Grundlagen. Bereit für deine erste Mission auf der Grünen Piste?",
        level1Name: "Grüne Piste - Les Marmottes",
        level1Task: "Präpariere die Anfängerpiste",
        level2Name: "Blaue Piste - Le Chamois",
        level2Task: "Präpariere effizient vor der Öffnung",
        level3Name: "Snowpark - Air Zone",
        level3Task: "Bereite die Freestyle-Module vor",
        level4Name: "Rote Piste - L'Aigle",
        level4Task: "Steiles Terrain, Kraftstoff managen",
        level5Name: "Halfpipe - Le Tube",
        level5Task: "Halfpipe für den Wettkampf vorbereiten",
        level6Name: "Schwarze Piste - La Verticale",
        level6Task: "Nachteinsatz mit Winde",
        level7Name: "Lawinenzone - Col Dangereux",
        level7Task: "Hochrisikogebiet vorbereiten",
        level8Name: "Sturm - Bergung",
        level8Task: "Pisten nach dem Sturm räumen",
        
        // Hazards
        cliffFall: "⚠️ ACHTUNG! Sie sind in die Schlucht gefallen! Mission gescheitert.",
        fuelEmpty: "⛽ LEER! Kein Tropfen Diesel mehr...",
        avalancheZone: "LAWINENZONE",
        riskLevelHigh: "HOCH",
        avalancheWarning: "⚠️ GEFAHR! Instabile Schneedecke! Verlasse die Zone!",
        avalancheTrigger: "🏔️💨 LAWINE AUSGELÖST! Keine Flucht möglich!",
        steepWarning: "⚠️ STEILER HANG! Benutze die Winde (SHIFT) oder du rutschst ab!",
        tumble: "🔄 ÜBERSCHLAG! Der Pistenbully ist umgekippt!",
        
        // Dialogues
        jeanPierreIntro: "Willkommen in Les Aiguilles Blanches, Kleiner! Ich bin Jean-Pierre, der Chefpräparierer.",
        level2Intro: "Gut gemacht gestern! Heute geht's zur blauen Piste.",
        level3Intro: "Der Snowpark braucht Liebe. Präzision!",
        level4Intro: "L'Aigle ist ernst. Achte auf den Kraftstoff. Die Pistenraupenspuren führen zurück nach oben — achte auf die gelb-schwarz gestreiften Stangen.",
        level4WinchIntro: "Du wirst nummerierte Ankerpfosten an steilen Hängen sehen. Drücke {winchKey} daneben, um die Winde einzuhaken — damit rutscht du nicht ab.",
        level4WinchIntroTouch: "Du wirst nummerierte Ankerpfosten an steilen Hängen sehen. Tippe auf den Winden-Button, um einzuhaken — damit rutscht du nicht ab.",
        level5Intro: "Morgen ist Wettkampf! Die Halfpipe muss perfekt sein.",
        level6Intro: "Nachteinsatz auf La Verticale. Benutze die Winde.",
        thierryWarning: "Achtung, die Lawinenzone ist empfindlich. Sei vorsichtig.",
        level8Intro: "Der Sturm ist vorbei. Nimm einen Glühwein, das wird lang!",
        marieWelcome: "Komm dich aufwärmen bei Marie. Eine leckere Tartiflette!",
        
        // Changelog
        changelogDate5: "7. Februar 2026",
        changelogDay5: "🎨 Retro-UI: 3D-Panels, Porträts, Schreibmaschinentext\n🏷️ Textlabels (FUEL, STAM, WINCH) statt Emojis\n🎯 Bonusziele pro Level\n🕹️ Gamepad-Tastenbelegung\n🎮 Gamepad-Navigation in allen Menüs",
        changelogDate4: "6. Februar 2026",
        changelogDay4: "🛤️ Befahrbare Pistenraupenspuren\n🕹️ Virtueller Joystick\n🌍 5 vollständige Sprachen",
        changelogDate3: "5. Februar 2026",
        changelogDay3: "🏔️ Felsige Klippen\n🌙 Nachtscheinwerfer\n🔗 Windenmechanik\n⌨️ Tastaturnavigation",
        changelogDate2: "4. Februar 2026",
        changelogDay2: "🎮 Gamepad-Unterstützung\n📱 Touch-Steuerung\n💪 Ausdauer\n💾 Speicherung\n♿ Barrierefreiheit",
        changelogDate1: "3. Februar 2026",
        changelogDay1: "🚜 Start: 9 Level, Tutorial\n❄️ Präparieren, Kraftstoff, Lawinen\n🏆 Credits und Fortschritt",

        // Taunts - Cliff
        tauntCliff1: "9 Tonnen in der Schlucht. Die Versicherung wird begeistert sein.",
        tauntCliff2: "Jean-Pierre sagte: 'Nicht zu nah am Rand!' Erinnerst du dich?",
        tauntCliff3: "Die Bergwacht kommt mit Seilen. Wieder.",
        tauntCliff4: "Marie storniert deine Raclette-Reservierung für heute Abend.",
        tauntCliff5: "Thierry rechnet bereits die Reparaturkosten...",
        // Taunts - Fuel
        tauntFuel1: "Die Anzeige war 10 Minuten lang auf Rot. Was hast du angeschaut?",
        tauntFuel2: "Émilie hatte 'TANKEN' in Großbuchstaben geschrieben.",
        tauntFuel3: "Selbst Diesel hat Grenzen. Du offenbar auch.",
        tauntFuel4: "Jean-Pierre seufzt. Er schickt Thierry mit einem Kanister.",
        tauntFuel5: "Die Sonne geht auf. Die Piste ist nicht präpariert.",
        // Taunts - Time
        tauntTime1: "Erster Sessellift in 3... 2... 1... Verpasst.",
        tauntTime2: "Skifahrer entdecken deine Piste. Buckelig. Vereist. Toll.",
        tauntTime3: "Jean-Pierre schaut auf seine Uhr, dann auf dich.",
        tauntTime4: "Die FIS fragt, warum der Slalom auf Suppe stattfindet.",
        tauntTime5: "Du hörst Skilehrer den Gästen erklären, dass es 'nicht ihre Schuld' ist.",
        // Taunts - Tumble
        tauntTumble1: "Die Winde ist nicht zur Dekoration da.",
        tauntTumble2: "Thierry starrt auf den Schaden. Sagt nichts. Das ist schlimmer.",
        tauntTumble3: "Jean-Pierre hat dir gezeigt, wie man ankert. Hast du geschlafen?",
        tauntTumble4: "Ein PistenBully kostet 400.000€. Naja, kostete.",
        tauntTumble5: "Der Hang schien machbar? Die Raupe war anderer Meinung.",
        // Taunts - Avalanche
        tauntAvalanche1: "Der Berg verzeiht selten. Er hat nicht verziehen.",
        tauntAvalanche2: "Météo France sagte Risikostufe 4. Hast du gelesen?",
        tauntAvalanche3: "Die Bergwacht findet die Raupe im Frühling. Vielleicht.",
        tauntAvalanche4: "Marie hört den Funkalarm. Sie weiß schon, dass du es warst.",
        tauntAvalanche5: "Das Lawinenteam hatte den Sektor gesichert. Du hast ihn ent-sichert."
    },
    
    it: {
        subtitle: "Simulazione Gatto delle Nevi",
        startGame: "Inizia",
        resumeGame: "Riprendi",
        newGame: "Nuova Partita",
        continue: "Continua",
        settings: "Impostazioni",
        controls: "Comandi",
        changelog: "Novità",
        howToPlay: "Come Giocare",
        howToPlayMove: "{keys} o Frecce per muoversi",
        howToPlayMoveHybrid: "{keys}/Frecce o D-pad touch",
        howToPlayGroom: "{groomKey} per preparare",
        howToPlayGroomHybrid: "{groomKey} o tocca ❄️",
        fullscreen: "Schermo intero",
        exitFullscreen: "Esci schermo intero",
        back: "Indietro",
        backToGame: "Torna al gioco",
        loading: "Caricamento...",
        madeIn: "Fatto con ❄️ in Savoia",
        on: "✓ SÌ",
        off: "✗ NO",
        zoneClosed: "🚫 ZONA CHIUSA",
        
        // Settings
        language: "Lingua",
        accessibility: "Accessibilità",
        highContrast: "Alto Contrasto",
        reducedMotion: "Meno Movimento",
        colorblindMode: "Daltonismo",
        none: "Nessuno",
        deuteranopia: "Deuteran.",
        protanopia: "Protan.",
        tritanopia: "Tritan.",
        move: "Muovi",
        moveUp: "Su",
        moveDown: "Giù",
        moveLeft: "Sinistra",
        moveRight: "Destra",
        groom: "Battipista",
        winch: "Verricello",
        pause: "Pausa",
        clickToRebind: "Clicca per modificare",
        pressKey: "Premi un tasto...",
        pressGamepadButton: "Premi un pulsante del gamepad...",
        gamepadButtons: "Pulsanti gamepad",
        saved: "Salvato!",
        resetControls: "Ripristina",
        controlsReset: "Comandi ripristinati!",
        keyboardLayout: "Layout tastiera",
        customBindings: "Personalizzato",
        gamepadSupported: "Gamepad OK",
        touchSupported: "Touch OK",
        noGamepadConnected: "Nessun gamepad connesso",
        
        // How to Play hints
        howToPlayMoveTouch: "Usa il D-pad virtuale",
        howToPlayMoveGamepad: "Stick o D-pad per muoversi",
        howToPlayGroomTouch: "Tocca ❄️ per preparare",
        howToPlayGroomGamepad: "per preparare la neve",
        howToPlayFuel: "Controlla carburante e resistenza!",
        
        // Winch
        winchAttached: "🔗 Verricello agganciato! Tieni {winchKey} per assistenza.",
        winchActive: "VERRICELLO",
        winchHint: "Premi {winchKey} vicino a un paletto di ancoraggio numerato per il verricello",
        winchHintTouch: "Tieni 🔗 per il verricello",
        accessPath: "Strada di servizio",
        toPiste: "Verso la pista",
        
        // Game
        paused: "Pausa",
        resume: "Riprendi",
        quitToMenu: "Torna al Menu",
        levelComplete: "Livello completato!",
        levelFailed: "Livello fallito",
        tryAgain: "Riprova",
        coverage: "Copertura",
        time: "Tempo",
        target: "Obiettivo",
        rating: "Voto",
        nextLevel: "Prossimo livello",
        replay: "Rigiocare",
        pressContinue: "Premi Spazio o tocca per continuare",
        pauseTitle: "⏸️ Pausa",
        restart: "Ricomincia",
        quit: "Esci",
        menu: "Menu",
        tutorial: "Tutorial",
        timeUsed: "Tempo impiegato",
        excellent: "Eccellente!",
        good: "Ben fatto!",
        passed: "Superato",
        bonusFuel: "Carburante usato",
        bonusNoTumble: "Nessuna caduta",
        bonusSpeed: "Tempo",
        bonusWinch: "Usi del verricello",
        bonusExplore: "Strade esplorate",
        retry: "Riprova",
        gameComplete: "Gioco completato!",
        viewCredits: "Vedi crediti",
        creditsTitle: "Complimenti!",
        creditsSubtitle: "Hai padroneggiato Les Aiguilles Blanches",
        playAgain: "Rigiocare",
        skipCredits: "Premi un tasto per saltare",
        fr: "Francese",
        
        // Levels - Tutorial step by step
        tutorialName: "Tutorial - Primi Passi",
        tutorialTask: "Impara le basi",
        tutorialIntro: "Benvenuto a Les Aiguilles Blanches!",
        tutorialWelcome: "🏔️ Benvenuto, novellino! Sono Jean-Pierre, capo gattista. Ti insegnerò il mestiere.",
        tutorialControls: "🎮 COMANDI: Usa {keys} o le frecce ↑↓←→ per muovere il gatto delle nevi.",
        tutorialControlsTouch: "🎮 COMANDI: Usa il D-pad ◀▲▼▶ a sinistra per muoversi.",
        tutorialControlsGamepad: "🎮 COMANDI: Stick sinistro o D-pad per muoversi.",
        tutorialMove: "👆 PROVA: Muoviti sulla pista. La neve bianca deve essere battuta!",
        tutorialGroomIntro: "✅ Ottimo! Ora impariamo a battere la neve.",
        tutorialGroomAction: "❄️ BATTIPISTA: Tieni {groomKey} mentre ti muovi per lisciare la neve.",
        tutorialGroomActionTouch: "❄️ BATTIPISTA: Tieni il pulsante ❄️ a destra per preparare.",
        tutorialGroomActionGamepad: "❄️ BATTIPISTA: Tieni {groomKey} mentre ti muovi per preparare.",
        tutorialCoverage: "📊 Vedi? La neve diventa più liscia! Continua a battere!",
        tutorialHUD: "📈 HUD: In alto a sinistra: ⛽ Carburante, 💪 Resistenza, ❄️ Copertura. In alto a destra: ⏱️ Tempo e 🎯 Obiettivo.",
        tutorialGoal: "🎯 OBIETTIVO: Batti almeno il 40% della pista prima che scada il tempo. Gli sciatori stanno arrivando!",
        tutorialFuel: "⛽ CARBURANTE: Muoversi consuma carburante. Durante le missioni, visita la stazione di servizio!",
        tutorialComplete: "🏆 Bravo! Hai imparato le basi. Pronto per la tua prima missione sulla Pista Verde?",
        level1Name: "Pista Verde - Les Marmottes",
        level1Task: "Prepara la pista principianti",
        level2Name: "Pista Blu - Le Chamois",
        level2Task: "Prepara prima dell'apertura",
        level3Name: "Snowpark - Air Zone",
        level3Task: "Prepara i moduli freestyle",
        level4Name: "Pista Rossa - L'Aigle",
        level4Task: "Terreno ripido, gestisci il carburante",
        level5Name: "Halfpipe - Le Tube",
        level5Task: "Prepara l'halfpipe per la gara",
        level6Name: "Pista Nera - La Verticale",
        level6Task: "Operazione notturna con verricello",
        level7Name: "Zona Valanghe - Col Dangereux",
        level7Task: "Prepara la zona ad alto rischio",
        level8Name: "Tempesta - Recupero",
        level8Task: "Libera le piste dopo la tempesta",
        
        // Hazards
        cliffFall: "⚠️ ATTENZIONE! Sei caduto nel dirupo! Missione fallita.",
        fuelEmpty: "⛽ SERBATOIO VUOTO! Neanche una goccia di diesel...",
        avalancheZone: "ZONA VALANGHE",
        riskLevelHigh: "ALTO",
        avalancheWarning: "⚠️ PERICOLO! Manto nevoso instabile! Esci dalla zona!",
        avalancheTrigger: "🏔️💨 VALANGA INNESCATA! Impossibile evacuare!",
        steepWarning: "⚠️ PENDIO RIPIDO! Usa il verricello (SHIFT) o scivolerai!",
        tumble: "🔄 RIBALTAMENTO! Il gatto delle nevi si è rovesciato!",
        
        // Dialogues
        jeanPierreIntro: "Benvenuto a Les Aiguilles Blanches, piccolo! Sono Jean-Pierre, il capo gattista.",
        level2Intro: "Ben fatto ieri! Oggi si passa alla pista blu.",
        level3Intro: "Lo snowpark ha bisogno di cure. Precisione!",
        level4Intro: "L'Aigle è roba seria. Occhio al carburante. I tracciati battipista permettono di risalire — cerca i pali a strisce gialle e nere.",
        level4WinchIntro: "Vedrai paletti di ancoraggio numerati sui pendii ripidi. Premi {winchKey} vicino per agganciare il verricello — eviterai di scivolare.",
        level4WinchIntroTouch: "Vedrai paletti di ancoraggio numerati sui pendii ripidi. Tocca il pulsante verricello vicino per agganciarti — eviterai di scivolare.",
        level5Intro: "Domani c'è la gara! L'halfpipe deve essere perfetto.",
        level6Intro: "Operazione notturna su La Verticale. Usa il verricello.",
        thierryWarning: "Attenzione, la zona valanghe è sensibile. Fai attenzione.",
        level8Intro: "La tempesta è passata. Prendi un vin brulé, sarà lunga!",
        marieWelcome: "Vieni a scaldarti da Marie. Una bella tartiflette!",
        
        // Changelog
        changelogDate5: "7 febbraio 2026",
        changelogDay5: "🎨 UI retro: pannelli 3D, ritratti, effetto macchina da scrivere\n🏷️ Etichette testo (FUEL, STAM, WINCH) al posto degli emoji\n🎯 Obiettivi bonus per livello\n🕹️ Rimappatura tasti gamepad\n🎮 Navigazione gamepad in tutti i menu",
        changelogDate4: "6 febbraio 2026",
        changelogDay4: "🛤️ Tracciati battipista percorribili\n🕹️ Joystick virtuale\n🌍 5 lingue complete",
        changelogDate3: "5 febbraio 2026",
        changelogDay3: "🏔️ Scogliere rocciose\n🌙 Fari notturni\n🔗 Meccanica verricello\n⌨️ Navigazione tastiera",
        changelogDate2: "4 febbraio 2026",
        changelogDay2: "🎮 Supporto gamepad\n📱 Controlli touch\n💪 Resistenza\n💾 Salvataggio\n♿ Accessibilità",
        changelogDate1: "3 febbraio 2026",
        changelogDay1: "🚜 Lancio: 9 livelli, tutorial\n❄️ Preparazione, carburante, valanghe\n🏆 Crediti e progressione",

        // Taunts - Cliff
        tauntCliff1: "9 tonnellate nel burrone. L'assicurazione sarà entusiasta.",
        tauntCliff2: "Jean-Pierre aveva detto: 'Non troppo vicino al bordo!' Ricordi?",
        tauntCliff3: "Il soccorso alpino arriva con le corde. Di nuovo.",
        tauntCliff4: "Marie cancella la tua prenotazione per la raclette di stasera.",
        tauntCliff5: "Thierry sta già calcolando i costi di riparazione...",
        // Taunts - Fuel
        tauntFuel1: "L'indicatore era rosso da 10 minuti. Cosa guardavi?",
        tauntFuel2: "Émilie aveva scritto 'FARE RIFORNIMENTO' in maiuscolo.",
        tauntFuel3: "Anche il diesel ha i suoi limiti. Tu pure, a quanto pare.",
        tauntFuel4: "Jean-Pierre sospira. Manda Thierry con una tanica.",
        tauntFuel5: "Il sole sorge. La pista non è preparata.",
        // Taunts - Time
        tauntTime1: "Prima seggiovia tra 3... 2... 1... Persa.",
        tauntTime2: "Gli sciatori scoprono la tua pista. Dissestata. Ghiacciata. Magnifica.",
        tauntTime3: "Jean-Pierre guarda l'orologio, poi te.",
        tauntTime4: "La FIS chiede perché lo slalom è su una zuppa.",
        tauntTime5: "Senti i maestri di sci spiegare ai clienti che 'non è colpa loro'.",
        // Taunts - Tumble
        tauntTumble1: "Il verricello non è decorativo. È per pendii come questo.",
        tauntTumble2: "Thierry fissa i danni. Non dice niente. È peggio.",
        tauntTumble3: "Jean-Pierre ti ha mostrato come ancorarti. Dormivi?",
        tauntTumble4: "Un PistenBully costa 400.000€. Beh, costava.",
        tauntTumble5: "Il pendio sembrava gestibile? Il gatto non era d'accordo.",
        // Taunts - Avalanche
        tauntAvalanche1: "La montagna perdona raramente. Non ha perdonato.",
        tauntAvalanche2: "Météo France diceva rischio 4. L'hai letto?",
        tauntAvalanche3: "Il soccorso troverà il gatto in primavera. Forse.",
        tauntAvalanche4: "Marie sente l'allarme radio. Sa già che sei tu.",
        tauntAvalanche5: "La squadra valanghe aveva messo in sicurezza il settore. Tu l'hai de-sicurato."
    },
    
    es: {
        subtitle: "Simulación de Pisapistas",
        startGame: "Empezar",
        resumeGame: "Continuar Partida",
        newGame: "Nueva Partida",
        continue: "Continuar",
        settings: "Ajustes",
        controls: "Controles",
        changelog: "Novedades",
        howToPlay: "Cómo Jugar",
        howToPlayMove: "{keys} o Flechas para mover",
        howToPlayMoveHybrid: "{keys}/Flechas o D-pad táctil",
        howToPlayGroom: "{groomKey} para preparar",
        howToPlayGroomHybrid: "{groomKey} o toca ❄️",
        fullscreen: "Pantalla completa",
        exitFullscreen: "Salir pantalla completa",
        back: "Volver",
        backToGame: "Volver al juego",
        loading: "Cargando...",
        madeIn: "Hecho con ❄️ en Saboya",
        on: "✓ SÍ",
        off: "✗ NO",
        zoneClosed: "🚫 ZONA CERRADA",
        
        // Settings
        language: "Idioma",
        accessibility: "Accesibilidad",
        highContrast: "Alto Contraste",
        reducedMotion: "Menos Movimiento",
        colorblindMode: "Daltonismo",
        none: "Ninguno",
        deuteranopia: "Deuteran.",
        protanopia: "Protan.",
        tritanopia: "Tritan.",
        move: "Mover",
        moveUp: "Arriba",
        moveDown: "Abajo",
        moveLeft: "Izquierda",
        moveRight: "Derecha",
        groom: "Pisar",
        winch: "Cabrestante",
        pause: "Pausa",
        clickToRebind: "Clic para cambiar",
        pressKey: "Pulsa una tecla...",
        pressGamepadButton: "Pulsa un botón del mando...",
        gamepadButtons: "Botones del mando",
        saved: "¡Guardado!",
        resetControls: "Restablecer",
        controlsReset: "¡Controles restablecidos!",
        keyboardLayout: "Distribución",
        customBindings: "Personalizado",
        gamepadSupported: "Gamepad OK",
        touchSupported: "Táctil OK",
        noGamepadConnected: "Ningún gamepad conectado",
        
        // How to Play hints
        howToPlayMoveTouch: "Usa el D-pad virtual",
        howToPlayMoveGamepad: "Stick o D-pad para mover",
        howToPlayGroomTouch: "Toca ❄️ para preparar",
        howToPlayGroomGamepad: "para preparar la nieve",
        howToPlayFuel: "¡Vigila el combustible y la resistencia!",
        
        // Winch
        winchAttached: "🔗 ¡Cabrestante enganchado! Mantén {winchKey} para asistencia.",
        winchActive: "CABRESTANTE",
        winchHint: "Pulsa {winchKey} cerca de un poste de anclaje numerado para usar el cabrestante",
        winchHintTouch: "Mantén 🔗 para el cabrestante",
        accessPath: "Camino de servicio",
        toPiste: "Hacia la pista",
        
        // Game
        paused: "Pausado",
        resume: "Reanudar",
        quitToMenu: "Volver al Menú",
        levelComplete: "¡Nivel completado!",
        levelFailed: "Nivel fallido",
        tryAgain: "Reintentar",
        coverage: "Cobertura",
        time: "Tiempo",
        target: "Objetivo",
        rating: "Puntuación",
        nextLevel: "Siguiente nivel",
        replay: "Rejugar",
        pressContinue: "Pulsa Espacio o toca para continuar",
        pauseTitle: "⏸️ Pausa",
        restart: "Reiniciar",
        quit: "Salir",
        menu: "Menú",
        tutorial: "Tutorial",
        timeUsed: "Tiempo usado",
        excellent: "¡Excelente!",
        good: "¡Bien hecho!",
        passed: "Aprobado",
        bonusFuel: "Combustible usado",
        bonusNoTumble: "Sin caídas",
        bonusSpeed: "Tiempo",
        bonusWinch: "Usos del cabrestante",
        bonusExplore: "Caminos explorados",
        retry: "Reintentar",
        gameComplete: "¡Juego completado!",
        viewCredits: "Ver créditos",
        creditsTitle: "¡Felicidades!",
        creditsSubtitle: "Has dominado Les Aiguilles Blanches",
        playAgain: "Jugar de nuevo",
        skipCredits: "Pulsa una tecla para saltar",
        fr: "Francés",
        
        // Levels - Tutorial step by step
        tutorialName: "Tutorial - Primeros Pasos",
        tutorialTask: "Aprende lo básico",
        tutorialIntro: "¡Bienvenido a Les Aiguilles Blanches!",
        tutorialWelcome: "🏔️ ¡Bienvenido, novato! Soy Jean-Pierre, jefe pisador. Te enseñaré el oficio.",
        tutorialControls: "🎮 CONTROLES: Usa {keys} o las flechas ↑↓←→ para mover la máquina pisanieves.",
        tutorialControlsTouch: "🎮 CONTROLES: Usa el D-pad ◀▲▼▶ a la izquierda para moverte.",
        tutorialControlsGamepad: "🎮 CONTROLES: Stick izquierdo o D-pad para moverte.",
        tutorialMove: "👆 PRUEBA: Muévete por la pista. ¡La nieve blanca debe ser pisada!",
        tutorialGroomIntro: "✅ ¡Genial! Ahora aprendamos a pisar la nieve.",
        tutorialGroomAction: "❄️ PISAR: Mantén {groomKey} mientras te mueves para alisar la nieve.",
        tutorialGroomActionTouch: "❄️ PISAR: Mantén el botón ❄️ a la derecha para preparar.",
        tutorialGroomActionGamepad: "❄️ PISAR: Mantén {groomKey} mientras te mueves para preparar.",
        tutorialCoverage: "📊 ¿Ves? ¡La nieve se vuelve más lisa! ¡Sigue pisando!",
        tutorialHUD: "📈 HUD: Arriba izquierda: ⛽ Combustible, 💪 Resistencia, ❄️ Cobertura. Arriba derecha: ⏱️ Tiempo y 🎯 Objetivo.",
        tutorialGoal: "🎯 META: Pisa al menos el 40% de la pista antes de que acabe el tiempo. ¡Los esquiadores vienen!",
        tutorialFuel: "⛽ COMBUSTIBLE: Moverse gasta combustible. ¡En misiones, visita la gasolinera!",
        tutorialComplete: "🏆 ¡Bravo! Dominas lo básico. ¿Listo para tu primera misión en la Pista Verde?",
        level1Name: "Pista Verde - Les Marmottes",
        level1Task: "Prepara la pista de principiantes",
        level2Name: "Pista Azul - Le Chamois",
        level2Task: "Prepara antes de la apertura",
        level3Name: "Snowpark - Air Zone",
        level3Task: "Prepara los módulos de freestyle",
        level4Name: "Pista Roja - L'Aigle",
        level4Task: "Terreno empinado, gestiona el combustible",
        level5Name: "Halfpipe - Le Tube",
        level5Task: "Prepara el halfpipe para la competición",
        level6Name: "Pista Negra - La Verticale",
        level6Task: "Operación nocturna con cabrestante",
        level7Name: "Zona de Avalanchas - Col Dangereux",
        level7Task: "Prepara la zona de alto riesgo",
        level8Name: "Tormenta - Recuperación",
        level8Task: "Despeja las pistas tras la tormenta",
        
        // Hazards
        cliffFall: "⚠️ ¡CUIDADO! ¡Has caído al precipicio! Misión fallida.",
        fuelEmpty: "⛽ ¡SIN COMBUSTIBLE! Ni una gota de diésel...",
        avalancheZone: "ZONA DE AVALANCHAS",
        riskLevelHigh: "ALTO",
        avalancheWarning: "⚠️ ¡PELIGRO! ¡Manto de nieve inestable! ¡Sal de la zona!",
        avalancheTrigger: "🏔️💨 ¡AVALANCHA DESENCADENADA! ¡Evacuación imposible!",
        steepWarning: "⚠️ ¡PENDIENTE EMPINADA! ¡Usa el cabrestante (SHIFT) o resbalarás!",
        tumble: "🔄 ¡VUELCO! ¡La máquina ha volcado en la pendiente!",
        
        // Dialogues
        jeanPierreIntro: "¡Bienvenido a Les Aiguilles Blanches, pequeño! Soy Jean-Pierre, el jefe pisador.",
        level2Intro: "¡Bien hecho ayer! Hoy pasamos a la pista azul.",
        level3Intro: "El snowpark necesita cariño. ¡Precisión!",
        level4Intro: "L'Aigle es serio. Vigila el combustible. Los caminos de pisapistas permiten subir — busca los postes con rayas amarillas y negras.",
        level4WinchIntro: "Verás postes de anclaje numerados en las pendientes pronunciadas. Pulsa {winchKey} cerca para enganchar el cabrestante — evitarás resbalar.",
        level4WinchIntroTouch: "Verás postes de anclaje numerados en las pendientes pronunciadas. Toca el botón de cabrestante cerca para engancharte — evitarás resbalar.",
        level5Intro: "¡Mañana hay competición! El halfpipe debe estar perfecto.",
        level6Intro: "Operación nocturna en La Verticale. Usa el cabrestante.",
        thierryWarning: "Cuidado, la zona de avalanchas es sensible. Ten cuidado.",
        level8Intro: "La tormenta ha pasado. ¡Toma un vino caliente, va a ser largo!",
        marieWelcome: "Ven a calentarte a lo de Marie. ¡Una buena tartiflette!",
        
        // Changelog
        changelogDate5: "7 de febrero de 2026",
        changelogDay5: "🎨 UI retro: paneles 3D, retratos, efecto máquina de escribir\n🏷️ Etiquetas texto (FUEL, STAM, WINCH) en vez de emojis\n🎯 Objetivos bonus por nivel\n🕹️ Reasignación botones mando\n🎮 Navegación mando en todos los menús",
        changelogDate4: "6 de febrero de 2026",
        changelogDay4: "🛤️ Caminos de pisapistas transitables\n🕹️ Joystick virtual\n🌍 5 idiomas completos",
        changelogDate3: "5 de febrero de 2026",
        changelogDay3: "🏔️ Acantilados rocosos\n🌙 Faros nocturnos\n🔗 Mecánica cabrestante\n⌨️ Navegación teclado",
        changelogDate2: "4 de febrero de 2026",
        changelogDay2: "🎮 Soporte mando\n📱 Controles táctiles\n💪 Resistencia\n💾 Guardado\n♿ Accesibilidad",
        changelogDate1: "3 de febrero de 2026",
        changelogDay1: "🚜 Lanzamiento: 9 niveles, tutorial\n❄️ Preparación, combustible, avalanchas\n🏆 Créditos y progresión",

        // Taunts - Cliff
        tauntCliff1: "9 toneladas en el barranco. Al seguro le va a encantar.",
        tauntCliff2: "Jean-Pierre dijo: '¡No tan cerca del borde!' ¿Recuerdas?",
        tauntCliff3: "El equipo de rescate baja con cuerdas. Otra vez.",
        tauntCliff4: "Marie cancela tu reserva de raclette para esta noche.",
        tauntCliff5: "Thierry ya está calculando los costes de reparación...",
        // Taunts - Fuel
        tauntFuel1: "El indicador llevaba 10 minutos en rojo. ¿Qué mirabas?",
        tauntFuel2: "Émilie escribió 'REPOSTAR' en mayúsculas en la pizarra.",
        tauntFuel3: "Hasta el diésel tiene límites. Tú también, al parecer.",
        tauntFuel4: "Jean-Pierre suspira. Envía a Thierry con un bidón.",
        tauntFuel5: "Sale el sol. La pista no está preparada.",
        // Taunts - Time
        tauntTime1: "Primer telesilla en 3... 2... 1... Perdido.",
        tauntTime2: "Los esquiadores descubren tu pista. Con baches. Helada. Magnífica.",
        tauntTime3: "Jean-Pierre mira su reloj, luego a ti.",
        tauntTime4: "La FIS pregunta por qué el slalom está sobre sopa.",
        tauntTime5: "Oyes a los monitores explicar a los clientes que 'no es culpa suya'.",
        // Taunts - Tumble
        tauntTumble1: "El cabrestante no es decorativo. Es para pendientes así.",
        tauntTumble2: "Thierry contempla los daños. No dice nada. Es peor.",
        tauntTumble3: "Jean-Pierre te enseñó cómo anclarte. ¿Estabas dormido?",
        tauntTumble4: "Una PistenBully cuesta 400.000€. Bueno, costaba.",
        tauntTumble5: "¿La pendiente parecía manejable? La máquina no estaba de acuerdo.",
        // Taunts - Avalanche
        tauntAvalanche1: "La montaña rara vez perdona. No perdonó.",
        tauntAvalanche2: "Météo France dijo nivel de riesgo 4. ¿Lo leíste?",
        tauntAvalanche3: "El rescate encontrará la máquina en primavera. Quizás.",
        tauntAvalanche4: "Marie oye la alerta por radio. Ya sabe que eres tú.",
        tauntAvalanche5: "El equipo de avalanchas había asegurado el sector. Tú lo des-aseguraste."
    }
};

export function setLanguage(lang: SupportedLanguage): void {
    if (TRANSLATIONS[lang]) {
        currentLang = lang;
        localStorage.setItem(STORAGE_KEYS.LANG, lang);
    }
}

export function getLanguage(): SupportedLanguage {
    return currentLang;
}

export function t(key: string): string {
    return TRANSLATIONS[currentLang]?.[key] || TRANSLATIONS['en']?.[key] || key;
}

export function detectLanguage(): SupportedLanguage {
    const saved = localStorage.getItem(STORAGE_KEYS.LANG);
    if (saved && saved in TRANSLATIONS) {
        return saved as SupportedLanguage;
    }
    const browserLang = navigator.language.split('-')[0];
    return browserLang in TRANSLATIONS ? browserLang as SupportedLanguage : 'fr';
}

export function getSavedLanguage(): SupportedLanguage {
    return detectLanguage();
}
